openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /streaming/cfg"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    Set the streaming configuration for an Adapter.

    `/streaming/cfg`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PH2-API.oas3.yml#/components/securitySchemes"

tags:
  - name: Streaming Relocation Management
    description: Operations related to Streaming Services and Relocation

paths:
  /streaming/cfg:
    get:
      operationId: streamingCfgQuery
      tags:
        - Streaming Relocation Management
      summary: Query the streaming cfg for an adapter.
      description: |-
        # Usage
        For a particular Adapter, query its streaming configuration.  This call
        will reflect the current applied configuration and any pending but
        unconfirmed configuration changes.

        ## Parameters
          - **id**: The id of the adapter to retrieve the current streaming
          configuration for.

      parameters:
        - in: query
          name: id
          required: true
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
          example: "cd73b915-89a4-4971-9d86-bce91786b12a"
          description: |-
            The Adapter ID to query.

      responses:
        "200":
          description: |-
            Success, Streaming Service Configuration Returned.  This is an array
            of all streaming services, and their current configuration on the
            adapter.

            - **id**: the id of the streaming service
            - **country**: the country the streaming service is directed from.
            - **since**: The timestamp when the streaming service last changed.

          content:
            application/json:
              schema:
                $ref: "../../inc/adapter.oas3.yml#/components/schemas/streams-settings"
              example: [
                {
                  "id": "29a16e31-bb4d-4407-8244-8e68b820b854",
                  "country": "US",
                  "since": 1590834650124
                },
              ]

        "400":
          description: |-
            General Request processing error.  Possible errors are:
            * `"Internal Server Error."` - Fatal uncategorized error in server.
            * `"Required Parameters missing or malformed."` - JSON Message Body
            Error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Internal Server Error."
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "404":
          $ref: "../../inc/response.oas3.yml#/components/responses/404"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        default:
          $ref: "../../inc/response.oas3.yml#/components/responses/default"


    post:
      operationId: streamingCfgSet
      tags:
        - Streaming Relocation Management
      summary: Set the streaming cfg for an adapter.
      description: |-
        # Usage
        For a particular Adapter, set its streaming configuration.  Will respond
        with the current configuration and a pending time stamp that can be
        compared against since to determine if the setting has been applied or
        not.

        ## Parameters
          - **id**: The id of the stream to configure.
          - **adapter**: The adapter ID to set the streaming config on.
          - **country**: The country to set the stream to.
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - id
                - adapter
                - country
              additionalProperties: false
              properties:
                id:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
                adapter:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
                country:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/iso3166-country"
              example:
                id: "29a16e31-bb4d-4407-8244-8e68b820b854"
                adapter: "cd73b915-89a4-4971-9d86-bce91786b12a"
                country: "GB"

      responses:
        "200":
          description: |-
            Success, Streaming Service Configuration Queued.
            - **id**: The id of the stream.
            - **adapter**: The adapter ID the streaming config relates to.
            - **country**: The country the stream is CURRENTLY set to.
            - **since**: The last time this stream config changed.
            - **pending**: The next timestamp which indicates the config has
            been changed.

          content:
            application/json:
              schema:
                $ref: "../../inc/adapter.oas3.yml#/components/schemas/stream-setting-queued"
              example:
                id: "29a16e31-bb4d-4407-8244-8e68b820b854"
                adapter: "cd73b915-89a4-4971-9d86-bce91786b12a"
                country: "US"
                since : 1590834650123
                pending : 1590841399785

        "400":
          description: |-
            General Request processing error.  Possible errors are:
            * `"Internal Server Error."` - Fatal uncategorized error in server.
            * `"Required Parameters missing or malformed."` - JSON Message Body
            Error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Internal Server Error."
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "404":
          $ref: "../../inc/response.oas3.yml#/components/responses/404"
        "415":
          $ref: "../../inc/response.oas3.yml#/components/responses/415"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        default:
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
