openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /streaming/cfg"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    Set the streaming configuration for an Adapter.

    `/streaming/cfg`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PH2-API.oas3.yml#/components/securitySchemes"

tags:
  - name: Streaming Relocation Management
    description: Operations related to Streaming Services and Relocation

paths:
  /streaming/cfg:
    get:
      operationId: streamingCfgQuery
      tags:
        - Streaming Relocation Management
      summary: Query the streaming cfg for an adapter.
      description: |-
        # Usage
        For a particular Adapter, query its streaming configuration.  This call
        will reflect the current applied configuration and any pending but
        unconfirmed configuration changes.
      parameters:
        - in: query
          name: id
          required: true
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
          example: "cd73b915-89a4-4971-9d86-bce91786b12a"
          description: |-
            The Adapter ID to query.

      responses:
        "200":
          description: |-
            Success, Streaming Service Configuration Queued.
          content:
            application/json:
              schema:
                $ref: "../../inc/adapter.oas3.yml#/components/schemas/streams-settings"
        "400":
          description: |-
            General Request processing error.  Possible errors are:
            * `"Internal Server Error."` - Fatal uncategorized error in server.
            * `"Required Parameters missing or malformed."` - JSON Message Body
            Error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Internal Server Error."
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "404":
          $ref: "../../inc/response.oas3.yml#/components/responses/404"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        default:
          $ref: "../../inc/response.oas3.yml#/components/responses/default"


    post:
      operationId: streamingCfgSet
      tags:
        - Streaming Relocation Management
      summary: Set the streaming cfg for an adapter.
      description: |-
        # Usage
        For a particular Adapter, set its streaming configuration.
      parameters:
        - in: query
          name: id
          required: true
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
          example: "cd73b915-89a4-4971-9d86-bce91786b12a"
          description: |-
            The Adapter ID to set.
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - id
                - cfg
              additionalProperties: false
              properties:
                id:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
                cfg:
                  $ref: "../../inc/adapter.oas3.yml#/components/schemas/stream-setting"
              example:
                id: "29a16e31-bb4d-4407-8244-8e68b820b854"
                cfg:
                  enabled: true
                  country: "JP"

      responses:
        "200":
          description: |-
            Success, Streaming Service Configuration Queued.
          content:
            application/json:
              schema:
                $ref: "../../inc/adapter.oas3.yml#/components/schemas/stream-settings"

        "400":
          description: |-
            General Request processing error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Could not query the adapter!"
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "415":
          $ref: "../../inc/response.oas3.yml#/components/responses/415"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        default:
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
