openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /streaming/cfg"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    Set the streaming configuration for an Adapter.

    `/streaming/cfg`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PHMothership.openapi.yml#/components/securitySchemes"

tags:
  - name: Streaming Relocation Management
    description: Operations related to Streaming Services and Relocation

paths:
  /streaming/cfg:
    post:
      operationId: streamingCfgQuery
      tags:
        - Streaming Relocation Management
      summary: Set the streaming cfg for an adapter.
      description:
        For a particular Adapter, set its streaming configuration.
      security:
        - clientToken: []
      parameters:
        - in: query
          name: id
          required: true
          schema:
            $ref: "../../inc/components.oas3.yml#/components/schemas/Custom/properties/guid"
          example: "cd73b915-89a4-4971-9d86-bce91786b12a"
          description: |-
            The Adapter ID to set.
        - in: query
          name: streamId
          required: true
          schema:
            $ref: "../../inc/components.oas3.yml#/components/schemas/Custom/properties/guid"
          example: "29a16e31-bb4d-4407-8244-8e68b820b854"
          description: |-
            The ID of the service, as obtained from the /streaming/services api
            call.
        - in: query
          name: enabled
          schema:
            type: boolean
            nullable: true
            example: null
          description: |-
            Optional: If set, can change if the relocation is enabled on the
            adapter for the service, or not.  If not set or null, the service
            enabled setting does not change.
        - in: query
          name: country
          schema:
            $ref: "../../inc/components.oas3.yml#/components/schemas/Custom/properties/iso3166-country"
          example: "UK"
          description: |-
            Optional: If set, can change the country the service is relocated
            to. If not set, the country is not changed.  Must be one of the
            available countries listed in the /streaming/services api call.

      responses:
        "200":
          description: |-
            Success, Streaming Service Configuration Queued.
          content:
            application/json:
              schema:
                $ref: "../../inc/components.oas3.yml#/components/schemas/Adapter-Settings"

        "400":
          description: |-
            General Request processing error.
          content:
            application/json:
              schema:
                $ref: "../../inc/components.oas3.yml#/components/schemas/Nack"
              example:
                error: "Could not query the adapter!"

        "403":
          description: |-
            Invalid Client Token, could not authorize api access.
          content:
            application/json:
              schema:
                $ref: "../../inc/components.oas3.yml#/components/schemas/GW_NegAuth"

        "500":
          description: |-
            An Internal server error occurred.  Operation failed.
          content:
            application/json:
              schema:
                $ref: "../../inc/components.oas3.yml#/components/schemas/GW_InternalError"

