openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /streaming/services"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    List one or all streaming services supported by the system.

    `/streaming/services`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PH2-API.oas3.yml#/components/securitySchemes"

tags:
  - name: Streaming Relocation Management
    description: Operations related to Streaming Services and Relocation

paths:
  /streaming/services:
    get:
      operationId: streamingServices
      tags:
        - Streaming Relocation Management
      summary: Lists streaming services, either ALL, or according to classification.
      description: |-
        # Usage

        Generates a list of streaming services currently supported by the
        system. The List is used to choose the streaming services to be set by
        the **/v1/streaming/cfg** api call.

        The call may return all services, or only Portable or Non-Portable
        services, as required.

        ## Security Requirements
          - **appKey** **MUST NOT** be present in the call.
          - **clientToken** **MUST** be present, not in need of renewal and
          valid.

        ## Parameters
          - **type**: The types of services to return, options are All,
         Portable and non-portable.

        A **Portable** Service is one where the one subscription may be used
        in multiple countries.  A client may use relocation to view any
        available stream where a proxy exists, or the stream from their current
        location, even if no proxy exists for it.

        A **Non-Portable** Service is region locked to the subscription.
        For example, a US Non-Portable Service can only view US content, and
        can not be relocated to view UK content.  For example, Relocation on these accounts
        allows a client with a US account, to view that content while in the UK.
        It will not allow a client with a US account to view content on the UK
        version of the service.
      parameters:
        - in: query
          name: type
          schema:
            type: string
            enum:
              - "All"
              - "Portable"
              - "Non-Portable"
            default: "All"
          example: "All"
          description: |-
            The filter to apply to the service list, the list can contain ALL
            services, or only Portable or Non-Portable services.
            If the parameter is missing the call will return ALL services.

      responses:
        "200":
          description: |-
            Success, The streaming service list.
          content:
            application/json:
              schema:
                $ref: "../../inc/adapter.oas3.yml#/components/schemas/streams"
              example: [
                  {
                    "id": "cd73b915-89a4-4971-9d86-bce91786b12a",
                    "name": "Netflix",
                    "icon": "netflix.ico",
                    "portable": true,
                    "countries": {
                      "proxy": [
                        "US", "GB", "AU", "TH"
                      ],
                      "non-proxy": [
                        "IL","ID"
                      ]
                    },
                  },
                  {
                    "id": "29a16e31-bb4d-4407-8244-8e68b820b854",
                    "name": "Disney+",
                    "icon": "disneyplus.ico",
                    "portable": false,
                    "countries": {
                      "proxy": [
                        "US", "GB", "IL",
                      ],
                      "non-proxy": [
                        "TH","ID"
                      ]
                    },
                  }
                ]

        "400":
          description: |-
            General Request processing error.  Possible errors are:
            * `"Internal Server Error."` - Fatal uncategorized error in server.
            * `"Required Parameters missing or malformed."` - JSON Message Body
            Error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Internal Server Error."
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "404":
          $ref: "../../inc/response.oas3.yml#/components/responses/404"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        default:
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
