###### HEADER INFO ##################
openapi: "3.0.2"
info:
  title: "Privacy Hero 2 - Mothership API - Components Specification"
  version: "1.0"
  description: |-
    The complete backend API for the Privacy Hero 2.

    The backend server infrastructure is known as the *"Mothership"*

    All general Schemas specifically related to authorization are defined here.
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

paths:
  /silence-lint:
    get:
      operationId: silenceLint
      description: dummy response to silence lint errors in this file
      tags:
        - Schema Definitions
      responses:
        "200":
          description: dummy response to silence lint errors in this file
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Authorized"
                  - $ref: "#/components/schemas/NotExpired"

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

tags:
  - name: Schema Definitions
    description: These are all schema definitions.

#########################################################
# Components are preformatted data that can be reused in definitions.
components:
  schemas:
    Authorized:
      type: object
      description: |-
        This response contains the clients credentials to use on subsequent API
        calls relating to the client.  These credentials uniquely identify the
        client and their account.

          - **bearer**: The Client Authorization Bearer token required to be
          sent in the **Authorization: Bearer** header of all API calls that are
          called on behalf of the Client.
          - **renew**: The Epoch Time, at which user access will expire with
          this token. Renew before this time, for uninterrupted access.  Renewal
          may occur up until **exp** time.
          - **exp**: The Epoch Time, at which the token will completely expire
          and may not be used for renewal.  After this time the user must
          re-authenticate to get a new bearer token.
          - **admin**: Present only when the logged in client is an admin user,
          and set to True.  It is not present when Admin is logged in as a
          client (impersonating the client).
          - **impersonator**: Present only when this client is being
          impersonated by an administrator. It is the email address of the admin
          user performing the impersonation.  Note, in all other regards this
          login is to be treated like a standard client login.

      required:
        - bearer
        - renew
        - exp
      additionalProperties: false
      properties:
        bearer:
          $ref: "simpletypes.oas3.yml#/components/schemas/ph2-bearer-token"
        renew:
          $ref: "simpletypes.oas3.yml#/components/schemas/epoch-timestamp-nonull"
        exp:
          $ref: "simpletypes.oas3.yml#/components/schemas/epoch-timestamp-nonull"
        admin:
          type: boolean
          nullable: true
          default: false
          description: |-
            **true**=The logged in user is an Admin user.
            If not present, the client is a normal user.  This field is only
            present and must be **true** IF the user is an Admin.
        impersonator:
          $ref: "simpletypes.oas3.yml#/components/schemas/email-address"

    NotExpired:
      type: object
      description: |-
        This response is sent if the request had expchk set to true, and the
        token expiry time has not yet passed.  The confirmation operation has
        not been performed when this is returned, it is only an indication that
        it is likely to succeed and has not yet expired.

          - **exp**: The Time the token expires.

      required:
        - exp
      additionalProperties: false
      properties:
        exp:
          $ref: "simpletypes.oas3.yml#/components/schemas/epoch-timestamp-nonull"
