###### HEADER INFO ##################
openapi: "3.0.2"
info:
  title: "Privacy Hero 2 - Mothership API - Components Specification"
  version: "1.0"
  description: |-
    The complete backend API for the Privacy Hero 2.

    The backend server infrastructure is known as the *"Mothership"*
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

paths:
  /silence-lint:
    get:
      operationId: silenceLint
      description: dummy response to silence lint errors in this file
      tags:
        - Account Management
      responses:
        "200":
          description: dummy response to silence lint errors in this file
          content:
              application/json:
                schema:
                  oneOf:
                    - $ref: "#/components/schemas/CustomProperties"
                    - $ref: "#/components/schemas/Adapter-Base"
                    - $ref: "#/components/schemas/Adapter-Unassociated"
                    - $ref: "#/components/schemas/Adapter-Unassociated-Array"
                    - $ref: "#/components/schemas/Adapter"

                    - $ref: "#/components/schemas/Adapters"
                    - $ref: "#/components/schemas/Device"
                    - $ref: "#/components/schemas/Devices"
                    - $ref: "#/components/schemas/AdapterDevices"
                    - $ref: "#/components/schemas/AdaptersDevices"
                    - $ref: "#/components/schemas/Profile"
                    - $ref: "#/components/schemas/Profiles"
                    - $ref: "#/components/schemas/ProfileDevices"
                    - $ref: "#/components/schemas/ProfilesDevices"
                    - $ref: "#/components/schemas/Ack"
                    - $ref: "#/components/schemas/Nack"
                    - $ref: "#/components/schemas/GW_NegAuth"
                    - $ref: "#/components/schemas/BadAppToken"
                    - $ref: "#/components/schemas/Authorized"
                    - $ref: "#/components/schemas/GW_InternalError"



###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

tags:
  - name: Account Management
    description: Operations related to Account Creation and Management

#########################################################
# Components are preformatted data that can be reused in definitions.
components:

  schemas:

    CustomProperties:
      # Define custom properties here, which we reuse in other schemas.
      # ONLY put properties here which are used in multiple schemas.
      type: object
      properties:
        # IP4 IP Address
        ip4:
          type: string
          format: "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"
          minLength: 7
          maxLength: 15
          description: |-
            An IP4 formatted IP Address
          example: "192.168.0.55"

        ip6:
          type: string
          format: "^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))$"
          minLength: 3
          maxLength: 45
          description: |-
            An IP6 formatted IP Address
          example: "2001:db8:85a3::8a2e:370:7334"

        # EUI-48 MAC Address
        mac:
          type: string
          format: "^(?:[[:xdigit:]]{2}([-:]))(?:[[:xdigit:]]{2}\\1){4}[[:xdigit:]]{2}$"
          maxLength: 17
          minLength: 17
          description: |-
            An EUI-48 formatted mac address.
          example: "00-00-5E-DF-98-EB"

        # Globally Unique ID
        guid:
          type: string
          format: "^[[:xdigit:]]{8}(-[[:xdigit:]]{4}){3}-[[:xdigit:]]{12}$"
          maxLength: 36
          minLength: 36
          description: |-
            Unique Identifier
          example: "cd73b915-89a4-4971-9d86-bce91786b12a"

        # Adapter Activation Code
        activation-code:
          type: string
          # format: "^...$"
          minLength: 9
          maxLength: 9
          description: |-
            Adapter/Router activation code.
          example: "????-????"

        # Type of Adapter
        adapter-type:
          type: string
          enum:
            - "Router-V1"
          description: |-
            The hardware type of the adapter/router.

        # Epoch Timestamp
        epoch-timestamp:
          type: integer
          description: |-
            A Time, expressed as seconds since Jan 01 1970. (UTC)
          example: 1587284382

        # ISO 3166 Country Codes
        iso3166-country:
          type: string
          format: "^[A-Z][A-Z]$"
          example: "US"
          minLength: 2
          maxLength: 2
          description: |-
            an ISO3166 country code


    # All Adapter records have these basic properties.
    Adapter-Base:
      type: object
      required:
        - mac
        - type
        - desc
      properties:
        mac:
          $ref: "#/components/schemas/CustomProperties/properties/mac"
        type:
          $ref: "#/components/schemas/CustomProperties/properties/adapter-type"
        desc:
          type: string
          description: |-
            A description of the hardware of the adapter/router.
          example: "Privacy Hero 2 - Router V1"

    Adapter-Unassociated:
      allOf:
        - $ref: "#/components/schemas/Adapter-Base"
        - type: object
          required:
            - since
          properties:
            since:
              $ref: "#/components/schemas/CustomProperties/properties/epoch-timestamp"
      description: |-
        * since - The time this adapter last came online.


    Adapter-Unassociated-Array:
      type: array
      items:
        $ref: "#/components/schemas/Adapter-Unassociated"

    Adapter:
      type: object
      required:
        - mac
        - desc
      allOf:
        - type: object
          required:
            - AdapterID
          properties:
            AdapterID:
              $ref: "#/components/schemas/CustomProperties/properties/guid"

        - $ref: "#/components/schemas/Adapter-Base"

        - type: object
          properties:
            name:
              type: string
              nullable: true
              default: null
              description: |-
                The Name assigned to the Adapter/Router by the Client.
            location:
              $ref: "#/components/schemas/CustomProperties/properties/iso3166-country"
            timezone:
              type: integer
              description: Local Timezone, number of minutes offset from UTC

            ip:
              type: object
              properties:
                lan:
                  type: object
                  properties:
                    ip4:
                      $ref: "#/components/schemas/CustomProperties/properties/ip4"
                    ip6:
                      $ref: "#/components/schemas/CustomProperties/properties/ip6"
                wan:
                  type: object
                  properties:
                    ip4:
                      $ref: "#/components/schemas/CustomProperties/properties/ip4"
                    ip6:
                      $ref: "#/components/schemas/CustomProperties/properties/ip6"
                vpn:
                  type: object
                  properties:
                    ip4:
                      $ref: "#/components/schemas/CustomProperties/properties/ip4"
                    ip6:
                      $ref: "#/components/schemas/CustomProperties/properties/ip6"

            registered:
              $ref: "#/components/schemas/CustomProperties/properties/epoch-timestamp"

            state:
              type: object
              properties:
                online:
                  type: boolean
                  description: |-
                    The state of the adapter/router.
                    * true - Online
                    * false - Offline
                since:
                  $ref: "#/components/schemas/CustomProperties/properties/epoch-timestamp"
                vpn:
                  type: boolean
                  description: |-
                    The state of VPN.
                    * true - VPN Active
                    * false - VPN In-active
                vpn-since:
                  $ref: "#/components/schemas/CustomProperties/properties/epoch-timestamp"

            settings:
              type: object
              properties:
                data-cap:
                  type: integer
                  description: Data cap in bytes per month.
                vpn:
                  type: boolean
                  description: |-
                    * true - Client wants the VPN enabled at the Adapter level
                    * false - Client want the VPN disabled at the Adapter level
                vpn-changed:
                  $ref: "#/components/schemas/CustomProperties/properties/epoch-timestamp"

                adblock:
                  type: boolean
                  description: |-
                    * true - Client wants the Ad blocking enabled at the Adapter level
                    * false - Client want the Ad blocking disabled at the Adapter level
                adblock-changed:
                  $ref: "#/components/schemas/CustomProperties/properties/epoch-timestamp"

                streaming:
                  type: boolean
                  description: |-
                    * true - Client wants Streaming Relocation enabled at the Adapter level
                    * false - Client want Streaming Relocation disabled at the Adapter level
                streaming-changed:
                  $ref: "#/components/schemas/CustomProperties/properties/epoch-timestamp"

                malware:
                  type: boolean
                  description: |-
                    * true - Client wants Malware/Phishing protection enabled at the Adapter level
                    * false - Client wants Malware/Phishing protection disabled at the Adapter level
                malware-changed:
                  $ref: "#/components/schemas/CustomProperties/properties/epoch-timestamp"

            diags:
              type: object
              properties:
                speed_test:
                  type: object
                  properties:
                    last:
                      type: integer
                      description: bits per second
                    last-when:
                      $ref: "#/components/schemas/CustomProperties/properties/epoch-timestamp"
                    best:
                      type: integer
                      description: bits per second
                    best-when:
                      $ref: "#/components/schemas/CustomProperties/properties/epoch-timestamp"
                ping_test:
                  type: object
                  properties:
                    last:
                      type: integer
                      description: milliseconds
                    last-when:
                      $ref: "#/components/schemas/CustomProperties/properties/epoch-timestamp"
                    best:
                      type: integer
                      description: milliseconds
                    best-when:
                      $ref: "#/components/schemas/CustomProperties/properties/epoch-timestamp"

    Adapters:
      type: array
      items:
        $ref: "#/components/schemas/Adapter"

    Device:
      type: object
      required:
        - mac
        - name
        - type
      properties:
        mac:
          type: string
          format: MAC Address
          example: "00-00-5E-32-5C-DE"
          description: Devices EUI-48 Formatted MAC Address
        name:
          type: string
          example: "android-e960b7e925b22464"
          description: The default name of the device
        type:
          type: string
          example: "Android Smart Phone"
          description: |-
            Automatically detected device type, used as `desc` if desc is null.
        given_name:
          type: string
          example: null
          description: If NOT null, this is the name the Client gave the device.
          nullable: true
        desc:
          type: string
          example: "Mums Samsung S12+"
          description: If not null, the Name given to the device by the user.
          nullable: true

    Devices:
      description: An array of known devices
      type: array
      items:
        $ref: "#/components/schemas/Device"

    AdapterDevices:
      description: An Adapter/Router and all it's known devices.
      #type: object
      #required:
      #  - mac
      #  - desc
      #properties:
        #mac:
        #  $ref: "#/components/schemas/Adapter/properties/mac"
        #desc:
        #  $ref: "#/components/schemas/Adapter/properties/desc"
        #name:
        #  $ref: "#/components/schemas/Adapter/properties/name"
        #devices:
        #  $ref: "#/components/schemas/Devices"

    AdaptersDevices:
      description: An array of adapters, and their devices.
      type: array
      items:
        $ref: "#/components/schemas/AdapterDevices"

    Profile:
      description: A device setting profile
      type: object
      properties:
        name:
          type: string
          description: The name given to the profile.

    Profiles:
      description: An array of known profiles
      type: array
      items:
        $ref: "#/components/schemas/Profile"

    ProfileDevices:
      description: |-
        A profiles, and the devices associated with it.
      allOf:
        - $ref: "#/components/schemas/Profile"
        - $ref: "#/components/schemas/Devices"

    ProfilesDevices:
      description: |-
        All profiles, and all devices in those profiles.
      type: array
      items:
        $ref: "#/components/schemas/ProfileDevices"

    Ack:
      type: object
      required:
        - msg
      properties:
        msg:
          type: string
          example: "OK."

    Nack:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: "Unauthorized"

    GW_NegAuth: # Negative Authorization from API Gateway
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: "User is not authorized to access this resource"

    GW_InternalError: # Internal gateway Server Error
      type: object
      required:
        - message
      properties:
        message:
          type: string
          nullable: true
          example: null

    #WWW-Authenticate: Bearer realm="example",
    #                       error="invalid_token",
    #                       error_description="The access token expired"
    BadAppToken:
      type: object

    Authorized:
      type: object
      required:
        - bearer
        - renew
        - exp
      properties:
        bearer:
          type: string
          example: kjlfhgaklhgkalhgkladhjg.kasdfakjshaksdjhakldjf
          description: |-
            The Client Authorization Bearer token required to be sent in the
            `Authorization: Bearer` header of all API calls that are called on
            behalf of the Client.
        renew:
          type: integer
          example: 234523454
          description: |-
            The Epoch Time, at which user access will expire with this token.
            Renew before this time, for uninterrupted access.  Renewal may occur
            up until `exp` time.
        exp:
          type: integer
          example: 234523454
          description: |-
            The Epoch Time, at which the token will completely expire and may
            not be used for renewal.  After this time the user must
            re-authenticate to get a new bearer token.
