###### HEADER INFO ##################
openapi: "3.0.2"
info:
  title: "Privacy Hero 2 - Mothership API - Components Specification"
  version: "1.0"
  description: |-
    The complete backend API for the Privacy Hero 2.

    The backend server infrastructure is known as the *"Mothership"*
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

paths:
  /silence-lint:
    get:
      operationId: silenceLint
      description: dummy response to silence lint errors in this file
      tags:
        - Schema Definitions
      responses:
        "200":
          description: dummy response to silence lint errors in this file
          content:
              application/json:
                schema:
                  oneOf:
                    - $ref: "#/components/schemas/streams"
                    - $ref: "#/components/schemas/Adapter-Base"
                    - $ref: "#/components/schemas/Adapter-Unassociated"
                    - $ref: "#/components/schemas/Adapter-Unassociated-Array"
                    - $ref: "#/components/schemas/Adapter-Settings"
                    - $ref: "#/components/schemas/Adapter"

                    - $ref: "#/components/schemas/Adapters"
                    - $ref: "#/components/schemas/Device"
                    - $ref: "#/components/schemas/Devices"
                    - $ref: "#/components/schemas/AdapterDevices"
                    - $ref: "#/components/schemas/AdaptersDevices"
                    - $ref: "#/components/schemas/Profile"
                    - $ref: "#/components/schemas/Profiles"
                    - $ref: "#/components/schemas/ProfileDevices"
                    - $ref: "#/components/schemas/ProfilesDevices"

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

tags:
  - name: Schema Definitions
    description: These are all schema definitions.

#########################################################
# Components are preformatted data that can be reused in definitions.
components:

  schemas:
    state:
      type: object
      required:
        - state
        - since
      properties:
        state:
          type: boolean
          nullable: true
          description: |-
            **true**=Active, **false**=Inactive, **null**=Unknown
        since:
          $ref: "./simpletypes.oas3.yml#/components/schemas/epoch-timestamp"
      description: |-
        The current known value of the state, and the time that it changed.

    speed-diag:
      type: object
      description: |-
        Speed Diagnostic Results. Negative values are estimated run time in seconds.
      required:
        - speed
        - when
      properties:
        speed:
          type: integer
          format: int32
          nullable: true
          description: |-
            **+VE** = bits per second speed result. **NULL** = Unknown. **-VE** = Test running.
        when:
          $ref: "./simpletypes.oas3.yml#/components/schemas/epoch-timestamp"

    wan-vpn-speed-diag:
      type: object
      description: Speed Diagnostic result for WAN and VPN Network
      required:
        - wan
        - vpn
      properties:
        wan:
          $ref: "#/components/schemas/speed-diag"
        vpn:
          $ref: "#/components/schemas/speed-diag"

    latency-diag:
      type: object
      description: latency diagnostic result
      required:
        - latency
        - when
      properties:
        latency:
          type: integer
          format: int32
          nullable: true
          description: |-
            **+VE** = millisecond latency result. **NULL** = Unknown. **-VE** = Test running.
        when:
          $ref: "./simpletypes.oas3.yml#/components/schemas/epoch-timestamp"

    wan-vpn-latency-diag:
      type: object
      description: Latency Diagnostic results for the WAN and VPN Networks
      required:
        - wan
        - vpn
      properties:
        wan:
          $ref: "#/components/schemas/latency-diag"
        vpn:
          $ref: "#/components/schemas/latency-diag"

    datacap:
      type: object
      description: A per-month Data Cap.
      properties:
        tx:
          type: integer
          format: uint64
          nullable: true
          description: |-
            Transmit Data Cap in Bytes per month. **null** = no tx data cap
        rx:
          type: integer
          format: uint64
          nullable: true
          description: |-
            Receive Data Cap in Bytes per month. **null** = no rx data cap
        combined:
          type: boolean
          default: false
          description: |-
            IF **true** then the tx data cap is the combined tx+rx data cap.

    wifi-settings:
      type: object
      description: Settings for an individual wifi network
      required:
        - active
        - ssid
        - key
      properties:
        active:
          type: boolean
          description: is the wifi network active.
          default: true
        ssid:
          type: string
          format: ssid
          minLength: 1
          maxLength: 32
          pattern: '^[^!#;+\]\/"\t][^+\]\/"\t]{0,30}[^ !#;+\]\/"\t]$|^[^ !#;+\]\/"\t]$'
          description: The SSID of the wifi network
          default: "PrivacyHero2"
          example: "PrivacyHero2"
        key:
          type: string
          format: WPA-PSK passphrase
          minLength: 8
          maxLength: 63
          pattern: "^[\u0020-\u007e]*$"
          nullable: true
          default: "r4nd0m k3y"
          example: "r4nd0m k3y"
          description: |-
            The WPA-PSK passphrase to secure the network. **null**=Open Wifi
            Network

    wlan-settings:
      type: object
      description: Settings for the Wireless Lan
      properties:
        2.4ghz:
          $ref: "#/components/schemas/wifi-settings"
        5ghz:
          $ref: "#/components/schemas/wifi-settings"

    stream-setting:
      type: object
      description: Settings for an individual relocatable stream
      properties:
        enabled:
          type: boolean
          default: true
          description: |-
            If the stream relocation is enabled for this service or not.
        country:
          $ref: "./simpletypes.oas3.yml#/components/schemas/iso3166-country"

    streams:
      type: array
      description: List of streaming services
      items:
        type: object
        description: Streaming Services
        required:
          - id
          - name
          - countries
          - portable
        properties:
          id:
            $ref: "./simpletypes.oas3.yml#/components/schemas/uuid"

          name:
            type: string
            minLength: 1
            maxLength: 64
            description: |-
              Name of the streaming service
            example: "Netflix"
          icon:
            $ref: "./simpletypes.oas3.yml#/components/schemas/url"
          portable:
            type: boolean
            description: |-
              Is the service subscription able to be used in multiple countries?
            default: true
          countries:
            type: object
            description: |-
              List of all countries streaming service is available in.

              **proxy** countries may be used to proxy a stream to appear as if
              the stream is being watched in that country.

              **non-proxy** are countries where the streaming service is
              available but for which no proxy exists.  These can only be
              used if the Adapter is located in that country.
            properties:
              proxy:
                type: array
                description: List of countries which can be proxied.
                items:
                  $ref: "./simpletypes.oas3.yml#/components/schemas/iso3166-country"
              non-proxy:
                type: array
                description: List of countries which can not be proxied.
                items:
                  $ref: "./simpletypes.oas3.yml#/components/schemas/iso3166-country"
          settings:
            type: object
            description: Settings for the service
            required:
              - current
            properties:
              current:
                $ref: "#/components/schemas/stream-setting"
              pending:
                $ref: "#/components/schemas/stream-setting"

    # All Adapter records have these basic properties.
    Adapter-Base:
      type: object
      required:
        - mac
        - type
        - desc
      properties:
        mac:
          $ref: "./simpletypes.oas3.yml#/components/schemas/mac"
        type:
          $ref: "./simpletypes.oas3.yml#/components/schemas/adapter-type"
        desc:
          type: string
          description: |-
            A description of the hardware of the adapter/router.
          example: "Privacy Hero 2 - Router V1"

    Adapter-Unassociated:
      allOf:
        - $ref: "#/components/schemas/Adapter-Base"
        - type: object
          required:
            - since
          properties:
            since:
              $ref: "./simpletypes.oas3.yml#/components/schemas/epoch-timestamp"
      description: |-
        * since - The time this adapter last came online.


    Adapter-Unassociated-Array:
      type: array
      items:
        $ref: "#/components/schemas/Adapter-Unassociated"

    Adapter-Settings:
      type: object
      properties:

        settings:
          type: object
          description: The settings of the Adapter/Router.
          properties:
            current:
              type: object
              description: The current settings.
              properties:
                wifi:
                  $ref: "#/components/schemas/wlan-settings"
                data-cap:
                  $ref: "#/components/schemas/datacap"
                vpn:
                  type: boolean
                  description: |-
                    VPN: **true**=Enabled, **false**=Disabled.
                adblock:
                  type: boolean
                  description: |-
                    Ad Blocking: **true**=Enabled, **false**=Disabled.
                streaming:
                  type: boolean
                  description: |-
                    Streaming Relocation: **true**=Enabled, **false**=Disabled
                malware:
                  type: boolean
                  description: |-
                    Malware/Phishing protection: **true**=Enabled, **false**=Disabled
            pending:
              type: object
              description: |-
                The settings we are attempting to set on the adapter.
              properties:
                wifi:
                  $ref: "#/components/schemas/wlan-settings"
                data-cap:
                  $ref: "#/components/schemas/datacap"
                vpn:
                  type: boolean
                  description: |-
                    VPN: **true**=enabling. **false**=disabling.
                adblock:
                  type: boolean
                  description: |-
                    Ad Blocking: **true**=enabling. **false**=disabling.
                streaming:
                  type: boolean
                  description: |-
                    Streaming Relocation: **true**=enabling. **false**=disabling.
                malware:
                  type: boolean
                  description: |-
                    Malware/Phishing protection: **true**=enabling, **false**=disabling.


    Adapter:
      type: object
      required:
        - mac
        - desc
      allOf:
        - type: object
          required:
            - AdapterID
          properties:
            AdapterID:
              $ref: "./simpletypes.oas3.yml#/components/schemas/uuid"

        - $ref: "#/components/schemas/Adapter-Base"

        - type: object
          required:
            - location
            - timezone
            - ip
            - registered
            - state
          properties:
            name:
              type: string
              nullable: true
              default: null
              example: "Home Office Router"
              description: |-
                The Name assigned to the Adapter/Router by the Client.
            location:
              $ref: "./simpletypes.oas3.yml#/components/schemas/iso3166-country"
            timezone:
              type: integer
              description: Local Timezone, number of minutes offset from UTC
              example: -300

            ip:
              type: object
              required:
                - lan
                - wan
                - vpn
              description: |-
                The current or last known IP addresses of the adapter/router.
              properties:
                lan:
                  type: object
                  required:
                    - ip4
                  description: The Local network IP addresses.
                  properties:
                    ip4:
                      $ref: "./simpletypes.oas3.yml#/components/schemas/ip4"
                    ip6:
                      $ref: "./simpletypes.oas3.yml#/components/schemas/ip6"
                wan:
                  type: object
                  required:
                    - ip4
                  description: The ISP Native IP addresses.
                  properties:
                    ip4:
                      $ref: "./simpletypes.oas3.yml#/components/schemas/ip4"
                    ip6:
                      $ref: "./simpletypes.oas3.yml#/components/schemas/ip6"
                vpn:
                  type: object
                  required:
                    - ip4
                  description: The VPN endpoint IP addresses.
                  properties:
                    ip4:
                      $ref: "./simpletypes.oas3.yml#/components/schemas/ip4"
                    ip6:
                      $ref: "./simpletypes.oas3.yml#/components/schemas/ip6"

            registered:
              $ref: "./simpletypes.oas3.yml#/components/schemas/epoch-timestamp"

            state:
              type: object
              description: The current state of the Adapter/Router.
              required:
                - online
                - vpn
                - ad-blocking
                - stream-relocation
                - malware-phising
              properties:
                online:
                  $ref: "#/components/schemas/state"
                vpn:
                  $ref: "#/components/schemas/state"
                ad-blocking:
                  $ref: "#/components/schemas/state"
                stream-relocation:
                  $ref: "#/components/schemas/state"
                malware-phising:
                  $ref: "#/components/schemas/state"

        - $ref: "#/components/schemas/Adapter-Settings"

        - type: object
          properties:
            diags:
              type: object
              description: Results from the last and best diagnostic tests
              properties:
                speed_test:
                  type: object
                  description: Network Speed test results
                  properties:
                    tx:
                      type: object
                      description: Transmit Speed Diagnostics
                      properties:
                        last:
                          $ref: "#/components/schemas/wan-vpn-speed-diag"
                        best:
                          $ref: "#/components/schemas/wan-vpn-speed-diag"

                    rx:
                      type: object
                      description: Receive Speed Diagnostics
                      properties:
                        last:
                          $ref: "#/components/schemas/wan-vpn-speed-diag"
                        best:
                          $ref: "#/components/schemas/wan-vpn-speed-diag"

                ping_test:
                  type: object
                  description: ping test latency results
                  properties:
                    last:
                      $ref: "#/components/schemas/wan-vpn-latency-diag"
                    best:
                      $ref: "#/components/schemas/wan-vpn-latency-diag"

    Adapters:
      type: array
      description: An Array of Adapter Records.
      items:
        $ref: "#/components/schemas/Adapter"

    Device:
      type: object
      required:
        - mac
        - name
        - type
      properties:
        mac:
          type: string
          format: MAC Address
          example: "00-00-5E-32-5C-DE"
          description: Devices EUI-48 Formatted MAC Address
        name:
          type: string
          example: "android-e960b7e925b22464"
          description: The default name of the device
        type:
          type: string
          example: "Android Smart Phone"
          description: |-
            Automatically detected device type, used as `desc` if desc is null.
        given_name:
          type: string
          example: null
          description: If NOT null, this is the name the Client gave the device.
          nullable: true
        desc:
          type: string
          example: "Mums Samsung S12+"
          description: If not null, the Name given to the device by the user.
          nullable: true

    Devices:
      description: An array of known devices
      type: array
      items:
        $ref: "#/components/schemas/Device"

    AdapterDevices:
      description: An Adapter/Router and all it's known devices.
      #type: object
      #required:
      #  - mac
      #  - desc
      #properties:
        #mac:
        #  $ref: "#/components/schemas/Adapter/properties/mac"
        #desc:
        #  $ref: "#/components/schemas/Adapter/properties/desc"
        #name:
        #  $ref: "#/components/schemas/Adapter/properties/name"
        #devices:
        #  $ref: "#/components/schemas/Devices"

    AdaptersDevices:
      description: An array of adapters, and their devices.
      type: array
      items:
        $ref: "#/components/schemas/AdapterDevices"

    Profile:
      description: A device setting profile
      type: object
      properties:
        name:
          type: string
          description: The name given to the profile.

    Profiles:
      description: An array of known profiles
      type: array
      items:
        $ref: "#/components/schemas/Profile"

    ProfileDevices:
      description: |-
        A profiles, and the devices associated with it.
      allOf:
        - $ref: "#/components/schemas/Profile"
        - $ref: "#/components/schemas/Devices"

    ProfilesDevices:
      description: |-
        All profiles, and all devices in those profiles.
      type: array
      items:
        $ref: "#/components/schemas/ProfileDevices"

