###### HEADER INFO ##################
openapi: "3.0.2"
info:
  title: "Privacy Hero 2 - Mothership API - Components Specification"
  version: "1.0"
  description: |-
    The complete backend API for the Privacy Hero 2.

    The backend server infrastructure is known as the *"Mothership"*
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

paths:
  /silence-lint:
    get:
      operationId: silenceLint
      description: dummy response to silence lint errors in this file
      tags:
        - Account Management
      responses:
        "200":
          description: dummy response to silence lint errors in this file
          content:
              application/json:
                schema:
                  oneOf:
                    - $ref: "#/components/schemas/Adapter"
                    - $ref: "#/components/schemas/Adapters"
                    - $ref: "#/components/schemas/Device"
                    - $ref: "#/components/schemas/Devices"
                    - $ref: "#/components/schemas/AdapterDevices"
                    - $ref: "#/components/schemas/AdaptersDevices"
                    - $ref: "#/components/schemas/Profile"
                    - $ref: "#/components/schemas/Profiles"
                    - $ref: "#/components/schemas/ProfileDevices"
                    - $ref: "#/components/schemas/ProfilesDevices"
                    - $ref: "#/components/schemas/Ack"
                    - $ref: "#/components/schemas/Nack"
                    - $ref: "#/components/schemas/GW_NegAuth"
                    - $ref: "#/components/schemas/BadAppToken"
                    - $ref: "#/components/schemas/Authorized"
                    - $ref: "#/components/schemas/GW_InternalError"



###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

tags:
  - name: Account Management
    description: Operations related to Account Creation and Management

#########################################################
# Components are preformatted data that can be reused in definitions.
components:

  schemas:
    Adapter:
      type: object
      required:
        - mac
        - desc
      properties:
        mac:
          type: string
          format: MAC Address
          example: "00-00-5E-78-9A-F0"
          description: Adapters EUI-48 Formatted MAC Address
        desc:
          type: string
          example: "Privacy Hero 2 - Router V1"
          description: The description of the adapters hardware.
        name:
          type: string
          example: "Main House Adapter"
          description: "The descriptive name the client has given the adapter"
          nullable: true
        since:
          type: string
          format: date-time
          example: "2023-04-12T23:20:50.52Z"
          description: The last time this device came online.

    Adapters:
      type: array
      items:
        $ref: "#/components/schemas/Adapter"

    Device:
      type: object
      required:
        - mac
        - name
        - type
      properties:
        mac:
          type: string
          format: MAC Address
          example: "00-00-5E-32-5C-DE"
          description: Devices EUI-48 Formatted MAC Address
        name:
          type: string
          example: "android-e960b7e925b22464"
          description: The default name of the device
        type:
          type: string
          example: "Android Smart Phone"
          description: |-
            Automatically detected device type, used as `desc` if desc is null.
        given_name:
          type: string
          example: null
          description: If NOT null, this is the name the Client gave the device.
          nullable: true
        desc:
          type: string
          example: "Mums Samsung S12+"
          description: If not null, the Name given to the device by the user.
          nullable: true

    Devices:
      description: An array of known devices
      type: array
      items:
        $ref: "#/components/schemas/Device"

    AdapterDevices:
      description: An Adapter/Router and all it's known devices.
      type: object
      required:
        - mac
        - desc
      properties:
        mac:
          $ref: "#/components/schemas/Adapter/properties/mac"
        desc:
          $ref: "#/components/schemas/Adapter/properties/desc"
        name:
          $ref: "#/components/schemas/Adapter/properties/name"
        devices:
          $ref: "#/components/schemas/Devices"

    AdaptersDevices:
      description: An array of adapters, and their devices.
      type: array
      items:
        $ref: "#/components/schemas/AdapterDevices"

    Profile:
      description: A device setting profile
      type: object
      properties:
        name:
          type: string
          description: The name given to the profile.

    Profiles:
      description: An array of known profiles
      type: array
      items:
        $ref: "#/components/schemas/Profile"

    ProfileDevices:
      description: |-
        A profiles, and the devices associated with it.
      allOf:
        - $ref: "#/components/schemas/Profile"
        - $ref: "#/components/schemas/Devices"

    ProfilesDevices:
      description: |-
        All profiles, and all devices in those profiles.
      type: array
      items:
        $ref: "#/components/schemas/ProfileDevices"

    Ack:
      type: object
      required:
        - msg
      properties:
        msg:
          type: string
          example: "OK."

    Nack:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: "Unauthorized"

    GW_NegAuth: # Negative Authorization from API Gateway
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: "User is not authorized to access this resource"

    GW_InternalError: # Internal gateway Server Error
      type: object
      required:
        - message
      properties:
        message:
          type: string
          nullable: true
          example: null

    #WWW-Authenticate: Bearer realm="example",
    #                       error="invalid_token",
    #                       error_description="The access token expired"
    BadAppToken:
      type: object

    Authorized:
      type: object
      required:
        - bearer
        - renew
        - exp
      properties:
        bearer:
          type: string
          example: kjlfhgaklhgkalhgkladhjg.kasdfakjshaksdjhakldjf
          description: |-
            The Client Authorization Bearer token required to be sent in the
            `Authorization: Bearer` header of all API calls that are called on
            behalf of the Client.
        renew:
          type: integer
          example: 234523454
          description: |-
            The Epoch Time, at which user access will expire with this token.
            Renew before this time, for uninterrupted access.  Renewal may occur
            up until `exp` time.
        exp:
          type: integer
          example: 234523454
          description: |-
            The Epoch Time, at which the token will completely expire and may
            not be used for renewal.  After this time the user must
            re-authenticate to get a new bearer token.
