###### HEADER INFO ##################
openapi: "3.0.2"
info:
  title: "Privacy Hero 2 - Mothership API - Components Specification"
  version: "1.0"
  description: |-
    The complete backend API for the Privacy Hero 2.

    The backend server infrastructure is known as the *"Mothership"*
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

paths:
  /silence-lint:
    get:
      operationId: silenceLint
      description: dummy response to silence lint errors in this file
      tags:
        - Schema Definitions
      responses:
        "200":
          description: dummy response to silence lint errors in this file
          content:
              application/json:
                schema:
                  oneOf:
                    - $ref: "#/components/schemas/Device"
                    - $ref: "#/components/schemas/Devices"
                    - $ref: "#/components/schemas/DeviceUsageHistory"

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

tags:
  - name: Schema Definitions
    description: These are all schema definitions.

#########################################################
# Components are preformatted data that can be reused in definitions.
components:

  schemas:

    DeviceIP:
      type: object
      required:
        - ip4
      additionalProperties: false
      properties:
        ip4:
          $ref: "./simpletypes.oas3.yml#/components/schemas/ip4"
        ip6:
          $ref: "./simpletypes.oas3.yml#/components/schemas/ip6"

    PauseSetting:
      type: object
      additionalProperties: false
      description: |-
        - **state**: if true the system is enabled persistently.
        - **pause**: if the time is greater than now, then regardless of the
        **state** the service is disabled, until the pause time elapses.  After
        which, the **state** reasserts itself.
      properties:
        state:
          type: boolean
          default: false
          description: |-
            **true** = ON.  **false** = Off
        pause:
          $ref: "./simpletypes.oas3.yml#/components/schemas/epoch-timestamp"

    DeviceConfig:
      type: object
      required:
        - vpn
        - device-protection
        - ad-blocking
      additionalProperties: false
      description: |-
        - **vpn**: Enabled or Not, and Pause time.
        - **Ad-blocking**: Enabled or Not, and Pause time.
        - **device-protection**: Enabled or not.  IF Pause time is greater than
        now, all internet for the device is blocked until pause time elapses.
      properties:
        vpn:
          $ref: "#/components/schemas/PauseSetting"
        ad-blocking:
          $ref: "#/components/schemas/PauseSetting"
        device-protection:
          $ref: "#/components/schemas/PauseSetting"

    DeviceUsageRecord:
      type: object
      required:
        - timestamp
        - tx
        - rx
      additionalProperties: false
      description: |-
        - **vpn**: Enabled or Not, and Pause time.
        - **Ad-blocking**: Enabled or Not, and Pause time.
        - **device-protection**: Enabled or not.  IF Pause time is greater than
        now, all internet for the device is blocked until pause time elapses.
      properties:
        timestamp:
          $ref: "./simpletypes.oas3.yml#/components/schemas/epoch-timestamp"
        tx:
          $ref: "./simpletypes.oas3.yml#/components/schemas/datausage"
        rx:
          $ref: "./simpletypes.oas3.yml#/components/schemas/datausage"

    DeviceUsageHistory:
      type: array
      description: |-
        Holds up to 90 days worth of hourly data usage records for the device.
        The resolution of the items (daily or hourly) depends on the api call.
      minItems: 1
      maxItems: 2160
      items:
        $ref: "#/components/schemas/DeviceUsageRecord"

    DeviceUsageSummary:
      type: object
      description: |-
        Holds a summary of the devices usage.
        - **hours24**: The last 24 hour agregated usage.
        - **week**: The last 7 days agregated usage.
        - **month**: The last 30 days agregated usage.
        - **quater**: The last 90 days agregated usage.

        **timestamp** in the device usage is the start of the period in question.
      additionalProperties: false
      properties:
        hours24:
          $ref: "#/components/schemas/DeviceUsageRecord"
        week:
          $ref: "#/components/schemas/DeviceUsageRecord"
        month:
          $ref: "#/components/schemas/DeviceUsageRecord"
        quater:
          $ref: "#/components/schemas/DeviceUsageRecord"


    Device:
      type: object
      required:
        - id
        - adapter
        - profile
        - mac
      additionalProperties: false
      properties:
        id:
          $ref: "./simpletypes.oas3.yml#/components/schemas/uuid"
        adapter:
          $ref: "./simpletypes.oas3.yml#/components/schemas/uuid"
        profile:
          $ref: "./simpletypes.oas3.yml#/components/schemas/uuid"
        mac:
          $ref: "./simpletypes.oas3.yml#/components/schemas/mac"
        name:
          $ref: "./simpletypes.oas3.yml#/components/schemas/device-name"
        type:
          $ref: "./simpletypes.oas3.yml#/components/schemas/device-name"
        manufacturer:
          $ref: "./simpletypes.oas3.yml#/components/schemas/device-name"
        given_name:
          $ref: "./simpletypes.oas3.yml#/components/schemas/device-name"
        given_type:
          $ref: "./simpletypes.oas3.yml#/components/schemas/device-name"
        given_manufacturer:
          $ref: "./simpletypes.oas3.yml#/components/schemas/device-name"
        ip:
          $ref: "#/components/schemas/DeviceIP"
        online:
          type: boolean
          default: true
        online_since:
          $ref: "./simpletypes.oas3.yml#/components/schemas/epoch-timestamp"
        discovered:
          $ref: "./simpletypes.oas3.yml#/components/schemas/epoch-timestamp"
        cfg:
          $ref: "#/components/schemas/DeviceConfig"
        usage:
          $ref: "#/components/schemas/DeviceUsageSummary"

    Devices:
      description: An array of known devices
      type: array
      minItems: 0
      maxItems: 512
      items:
        $ref: "#/components/schemas/Device"


