###### HEADER INFO ##################
openapi: "3.0.2"
info:
  title: "Privacy Hero 2 - Mothership API - Components Specification"
  version: "1.0"
  description: |-
    The complete backend API for the Privacy Hero 2.

    The backend server infrastructure is known as the *"Mothership"*
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

paths:
  /silence-lint:
    get:
      operationId: silenceLint
      description: dummy response to silence lint errors in this file
      tags:
        - Schema Definitions
      responses:
        "200":
          description: dummy response to silence lint errors in this file
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Device"
                  - $ref: "#/components/schemas/Devices"
                  - $ref: "#/components/schemas/DeviceUsageHistory"
                  - $ref: "#/components/schemas/Device-Settings"
                  - $ref: "#/components/schemas/Device-Settings-Reply"
                  - $ref: "#/components/schemas/DeviceSetBooleanCfg"
                  - $ref: "#/components/schemas/DeviceSetPauseCfg"
                  - $ref: "#/components/schemas/Device_Types"

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

tags:
  - name: Schema Definitions
    description: These are all schema definitions.

#########################################################
# Components are preformatted data that can be reused in definitions.
components:
  schemas:
    DeviceIP:
      type: object
      required:
        - ip4
      additionalProperties: false
      properties:
        ip4:
          $ref: "./simpletypes.oas3.yml#/components/schemas/ip4"
        ip6:
          $ref: "./simpletypes.oas3.yml#/components/schemas/ip6"

    DeviceConfig:
      type: object
      required:
        - vpn
        - device-protection
        - ad-blocking
      additionalProperties: false
      description: |-
        - **vpn**: Enabled or Not.
        - **Ad-blocking**: Enabled or Not.
        - **device-protection**: Enabled or not.
        - **internet-pause**: Internet will be paused until this time passes. If
          the value is 0 (zero), internet is paused indefinitely.
      properties:
        vpn:
          $ref: "./adapter.oas3.yml#/components/schemas/state"
        ad-blocking:
          $ref: "./adapter.oas3.yml#/components/schemas/state"
        device-protection:
          $ref: "./adapter.oas3.yml#/components/schemas/state"
        internet-pause:
          $ref: "./adapter.oas3.yml#/components/schemas/time-state"

    DeviceUsageRecord:
      type: object
      description: |-
        - **timestamp**: The start of the period.
        - **tx**: Number of bytes sent by the device in the period.
        - **rx**: Number of bytes received by the device in the period.
      required:
        - timestamp
        - tx
        - rx
      additionalProperties: false
      properties:
        timestamp:
          $ref: "./simpletypes.oas3.yml#/components/schemas/epoch-timestamp-nonull"
        tx:
          $ref: "./simpletypes.oas3.yml#/components/schemas/datausage"
        rx:
          $ref: "./simpletypes.oas3.yml#/components/schemas/datausage"

    DeviceUsageHistory:
      type: array
      description: |-
        Holds up to 90 days worth of hourly data usage records for the device.
        The resolution of the items (daily or hourly) depends on the api call.
      minItems: 1
      maxItems: 2160
      items:
        $ref: "#/components/schemas/DeviceUsageRecord"

    Device:
      type: object
      required:
        - id
        - adapter
        - profile
        - mac
      additionalProperties: false
      properties:
        id:
          $ref: "./simpletypes.oas3.yml#/components/schemas/uuid"
        adapter:
          $ref: "./simpletypes.oas3.yml#/components/schemas/uuid"
        profile:
          $ref: "./simpletypes.oas3.yml#/components/schemas/uuid"
        mac:
          $ref: "./simpletypes.oas3.yml#/components/schemas/mac"
        name:
          $ref: "./simpletypes.oas3.yml#/components/schemas/device-name"
        type:
          $ref: "./simpletypes.oas3.yml#/components/schemas/device-type"
        manufacturer:
          $ref: "./simpletypes.oas3.yml#/components/schemas/device-name"
        ip:
          $ref: "#/components/schemas/DeviceIP"
        online:
          type: boolean
          default: true
        online_since:
          $ref: "./simpletypes.oas3.yml#/components/schemas/epoch-timestamp"
        discovered:
          $ref: "./simpletypes.oas3.yml#/components/schemas/epoch-timestamp"
        cfg:
          $ref: "#/components/schemas/DeviceConfig"
      example:
        {
          "id": "e22cfd99-44e5-4c93-8cad-3185c623cc25",
          "adapter": "cd73b915-89a4-4971-9d86-bce91786b12a",
          "profile": "66f7346a-48af-4614-bd7b-6c17093d75e3",
          "mac": "00-00-5E-DF-98-EB",
          "name": "Nokia N78",
          "type": "Smartphone",
          "manufacturer": "Nokia",
          "ip":
            { "ip4": "192.168.0.55", "ip6": "2001:db8:85a3::8a2e:370:7334" },
          "online": true,
          "online_since": 1587732975,
          "discovered": 1587732975,
          "cfg":
            {
              "vpn": { "state": false, "since": 1587732975 },
              "ad-blocking": { "state": false, "since": 1587732975 },
              "device-protection": { "state": false, "since": 1587732975 },
              "internet-pause": { "state": 0, "since": 1587732975 },
            },
        }

    Devices:
      description: An array of known devices
      type: array
      minItems: 0
      maxItems: 512
      items:
        $ref: "#/components/schemas/Device"

    Device-Settings:
      type: object
      additionalProperties: false
      properties:
        settings:
          type: object
          description: |-
            The response to setting a device configuration.
            - **state** The services current state.
            - **since** The time the current state became set on the
            Adapter.
            - **pending** The requested state becomes valid when its **since**
            value equals or exceeds the returned **pending** value.
          required:
            - state
            - since
            - pending
          additionalProperties: false
          properties:
            state:
              type: boolean
              description: |-
                The current state of the requested service.
            since:
              $ref: "./simpletypes.oas3.yml#/components/schemas/epoch-timestamp-nonull"
            pending:
              $ref: "./simpletypes.oas3.yml#/components/schemas/epoch-timestamp-nonull"
          example:
            state: False
            since: 1589978803
            pending: 1590583603

    Device-Settings-Reply:
      type: object
      additionalProperties: false
      description: |-
        The response to setting an device service setting.
        - **state** The services current state.
        - **since** The time the current state became set for the device.
        - **pending** The requested state becomes valid when its
        **since** time stamp value equals or exceeds the returned **pending**
        time stamp.
      required:
        - state
        - since
        - pending
      properties:
        state:
          type: boolean
          description: |-
            The current state of the requested service.
        since:
          $ref: "./simpletypes.oas3.yml#/components/schemas/epoch-timestamp-nonull"
        pending:
          $ref: "./simpletypes.oas3.yml#/components/schemas/epoch-timestamp-nonull"
      example:
        state: False
        since: 1589978803
        pending: 1590583603

    DeviceSetBooleanCfg:
      type: object
      required:
        - id
        - service
        - setting
      additionalProperties: false
      properties:
        id:
          $ref: "./simpletypes.oas3.yml#/components/schemas/uuid"
        service:
          type: string
          enum:
            - "VPN"
            - "Ad-Blocking"
            - "Device-Protection"
        setting:
          type: boolean

    DeviceSetPauseCfg:
      type: object
      required:
        - id
        - service
        - setting
      additionalProperties: false
      properties:
        id:
          $ref: "./simpletypes.oas3.yml#/components/schemas/uuid"
        service:
          type: string
          enum:
            - "Internet-Pause"
        setting:
          $ref: "./simpletypes.oas3.yml#/components/schemas/epoch-timestamp-pause"

    Device_Type:
      type: object
      required:
        - name
        - icon
        - group
      additionalProperties: false
      properties:
        name:
          $ref: "./simpletypes.oas3.yml#/components/schemas/device-type"
        icon:
          $ref: "./simpletypes.oas3.yml#/components/schemas/url"
        group:
          $ref: "./simpletypes.oas3.yml#/components/schemas/device-group"

    Device_Types:
      description: An array of known device types
      type: array
      minItems: 1
      maxItems: 512
      items:
        $ref: "#/components/schemas/Device_Type"
