###### HEADER INFO ##################
openapi: "3.0.2"
info:
  title: "Privacy Hero 2 - Mothership API - Components Specification"
  version: "1.0"
  description: |-
    The complete backend API for the Privacy Hero 2.

    The backend server infrastructure is known as the *"Mothership"*
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

paths:
  /silence-lint:
    get:
      operationId: silenceLint
      description: dummy response to silence lint errors in this file
      tags:
        - Schema Definitions
      responses:
        "200":
          description: dummy response to silence lint errors in this file
          content:
              application/json:
                schema:
                  oneOf:
                    - $ref: "#/components/schemas/streams"
                    - $ref: "#/components/schemas/Adapter-Base"
                    - $ref: "#/components/schemas/Adapter-Unassociated"
                    - $ref: "#/components/schemas/Adapter-Unassociated-Array"
                    - $ref: "#/components/schemas/Adapter-Settings"
                    - $ref: "#/components/schemas/Adapter"

                    - $ref: "#/components/schemas/Adapters"
                    - $ref: "#/components/schemas/Device"
                    - $ref: "#/components/schemas/Devices"
                    - $ref: "#/components/schemas/AdapterDevices"
                    - $ref: "#/components/schemas/AdaptersDevices"
                    - $ref: "#/components/schemas/Profile"
                    - $ref: "#/components/schemas/Profiles"
                    - $ref: "#/components/schemas/ProfileDevices"
                    - $ref: "#/components/schemas/ProfilesDevices"

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

tags:
  - name: Schema Definitions
    description: These are all schema definitions.

#########################################################
# Components are preformatted data that can be reused in definitions.
components:

  schemas:

    Device:
      type: object
      required:
        - mac
        - name
        - type
      properties:
        mac:
          type: string
          format: MAC Address
          example: "00-00-5E-32-5C-DE"
          description: Devices EUI-48 Formatted MAC Address
        name:
          type: string
          example: "android-e960b7e925b22464"
          description: The default name of the device
        type:
          type: string
          example: "Android Smart Phone"
          description: |-
            Automatically detected device type, used as `desc` if desc is null.
        given_name:
          type: string
          example: null
          description: If NOT null, this is the name the Client gave the device.
          nullable: true
        desc:
          type: string
          example: "Mums Samsung S12+"
          description: If not null, the Name given to the device by the user.
          nullable: true

    Devices:
      description: An array of known devices
      type: array
      items:
        $ref: "#/components/schemas/Device"

    AdapterDevices:
      description: An Adapter/Router and all it's known devices.
      #type: object
      #required:
      #  - mac
      #  - desc
      #properties:
        #mac:
        #  $ref: "#/components/schemas/Adapter/properties/mac"
        #desc:
        #  $ref: "#/components/schemas/Adapter/properties/desc"
        #name:
        #  $ref: "#/components/schemas/Adapter/properties/name"
        #devices:
        #  $ref: "#/components/schemas/Devices"

    AdaptersDevices:
      description: An array of adapters, and their devices.
      type: array
      items:
        $ref: "#/components/schemas/AdapterDevices"

    Profile:
      description: A device setting profile
      type: object
      properties:
        name:
          type: string
          description: The name given to the profile.

    Profiles:
      description: An array of known profiles
      type: array
      items:
        $ref: "#/components/schemas/Profile"

    ProfileDevices:
      description: |-
        A profiles, and the devices associated with it.
      allOf:
        - $ref: "#/components/schemas/Profile"
        - $ref: "#/components/schemas/Devices"

    ProfilesDevices:
      description: |-
        All profiles, and all devices in those profiles.
      type: array
      items:
        $ref: "#/components/schemas/ProfileDevices"

