###### HEADER INFO ##################
openapi: "3.0.2"
info:
  title: "Privacy Hero 2 - Mothership API - Components Specification"
  version: "1.0"
  description: |-
    The complete backend API for the Privacy Hero 2.

    The backend server infrastructure is known as the *"Mothership"*
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

paths:
  /silence-lint:
    get:
      operationId: silenceLint
      description: dummy response to silence lint errors in this file
      tags:
        - Schema Definitions
      responses:
        "200":
          description: dummy response to silence lint errors in this file
          content:
              application/json:
                schema:
                  oneOf:
                    - $ref: "#/components/schemas/Profile"
                    - $ref: "#/components/schemas/Profiles"
                    - $ref: "#/components/schemas/ProfileDevices"
                    - $ref: "#/components/schemas/ProfilesDevices"
                    - $ref: "#/components/schemas/school-nights"

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

tags:
  - name: Schema Definitions
    description: These are all schema definitions.

#########################################################
# Components are preformatted data that can be reused in definitions.
components:

  schemas:

    Profile:
      description: |-
        A device settings profile.  Profiles define common settings for all
        associated devices.

        - **id**: The profiles unique id.
        - **adapter**: The unique id of the adapter the profile belongs to.
        - **name**: The descriptive name of the profile.
        - **icon**: An identifier for the icon.
        - **system**: Is this a system profile?  If so, can not be edited or
        deleted.
        - **settings**: Current state of settings for the profile.
      type: object
      required:
        - id
        - adapter
        - name
      additionalProperties: false
      properties:
        id:
          $ref: "./simpletypes.oas3.yml#/components/schemas/uuid"
        adapter:
          $ref: "./simpletypes.oas3.yml#/components/schemas/uuid"
        name:
          $ref: "./simpletypes.oas3.yml#/components/schemas/profile-name"
        icon:
          $ref: "./simpletypes.oas3.yml#/components/schemas/url"
        system:
          type: boolean
          default: false
          description: |-
            System profiles are fixed by the system.  They may not be modified,
            renamed or deleted.  Devices may be freely associated with them.
        settings:
          $ref: "#/components/schemas/ProfileSettings"

    #DataUsage:
    #  description: |-
    #    The aggregate monthly data usage of all devices connected to the profile.
    #  type: object
    #  additionalProperties: false
    #  properties:
    #    tx:
    #      $ref: "./simpletypes.oas3.yml#/components/schemas/datausage"
    #    rx:
    #      $ref: "./simpletypes.oas3.yml#/components/schemas/datausage"

    school-nights:
      type: array
      minItems: 7
      maxItems: 7
      description: |-
        This is a list of school nights for the week.  The first element is always
        MONDAY. The second is TUESDAY, and so on, until SUNDAY (the seventh
        item).  This selects the nights when a "school night" bedtime schedule
        will be used, or an "other night" schedule.
      items:
        type: boolean
      default: [true, true, true, true, false, false, true]
      example: [true, true, true, true, false, false, true]

    Bedtimes:
      description: |-
        The definition of bedtimes for a profile.

      type: object
      additionalProperties: false
      properties:
        enabled:
          type: boolean
          description: If the bedtime function is enabled or not.
        school-time:
          $ref: "./simpletypes.oas3.yml#/components/schemas/time-of-day-mins"
        other-time:
          $ref: "./simpletypes.oas3.yml#/components/schemas/time-of-day-mins"
        school-nights:
          $ref: "#/components/schemas/school-nights"

    ProfileSettings:
      description: |-
        The settings for a profile.
        - **youtube-restricted**: If youtube is restricted or normal.
        - **safesearch**: If search engines are forced to return safe results.
        - **internet-pause**: Internet will be paused until this time passes. If
          the value is negative, internet is paused indefinitely.
        - **bedtime**: A list of bedtimes, one for each day of a week.
        - **bedtime-delay**: A once off delay for the current days bedtime
        start.  Note, this does not change bedtime end.  This will automatically
        be reset back to zero when bedtime ends.
      type: object
      additionalProperties: false
      properties:
        youtube-restricted:
          type: boolean
          default: false
          description: If Youtube is restricted for all devices in this profile.
        safesearch:
          type: boolean
          default: false
          description: If search providers are forced to safe search.
        internet-pause:
          $ref: "./simpletypes.oas3.yml#/components/schemas/epoch-timestamp"
        bedtime:
          $ref: "#/components/schemas/Bedtimes"
        bedtime-delay:
          $ref: "./simpletypes.oas3.yml#/components/schemas/time-delay"

    Profiles:
      description: An array of known profiles
      type: array
      minItems: 1
      maxItems: 100
      items:
        $ref: "#/components/schemas/Profile"

    ProfileDevices:
      description: |-
        A profiles, and the devices associated with it.
      allOf:
        - $ref: "#/components/schemas/Profile"
        - $ref: "./device.oas3.yml#/components/schemas/Devices"

    ProfilesDevices:
      description: |-
        All profiles, and all devices in those profiles.
      type: array
      items:
        $ref: "#/components/schemas/ProfileDevices"

