###### HEADER INFO ##################
openapi: "3.0.2"
info:
  title: "Privacy Hero 2 - Mothership API - Components Specification"
  version: "1.0"
  description: |-
    The complete backend API for the Privacy Hero 2.

    The backend server infrastructure is known as the *"Mothership"*
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

paths:
  /silence-lint:
    get:
      operationId: silenceLint
      description: dummy response to silence lint errors in this file
      tags:
        - Schema Definitions
      responses:
        "200":
          description: dummy response to silence lint errors in this file
          content:
              application/json:
                schema:
                  oneOf:
                    - $ref: "#/components/schemas/Profile"
                    - $ref: "#/components/schemas/Profiles"
                    - $ref: "#/components/schemas/ProfileDevices"
                    - $ref: "#/components/schemas/ProfilesDevices"

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

tags:
  - name: Schema Definitions
    description: These are all schema definitions.

#########################################################
# Components are preformatted data that can be reused in definitions.
components:

  schemas:

    Profile:
      description: A device setting profile
      type: object
      properties:
        name:
          type: string
          description: The name given to the profile.

    Profiles:
      description: An array of known profiles
      type: array
      items:
        $ref: "#/components/schemas/Profile"

    ProfileDevices:
      description: |-
        A profiles, and the devices associated with it.
      allOf:
        - $ref: "#/components/schemas/Profile"
        - $ref: "./device.oas3.yml#/components/schemas/Devices"

    ProfilesDevices:
      description: |-
        All profiles, and all devices in those profiles.
      type: array
      items:
        $ref: "#/components/schemas/ProfileDevices"

