###### HEADER INFO ##################
openapi: "3.0.2"
info:
  title: "Privacy Hero 2 - Mothership API - Components Specification - Simple Types"
  version: "1.0"
  description: |-
    The complete backend API for the Privacy Hero 2.

    The backend server infrastructure is known as the *"Mothership"*

    This file defines simple types.
    Simple Types are not objects or arrays","and do not contain references to any
    other schema.
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

security:
  - clientToken: []

paths:
  /silence-lint:
    get:
      operationId: silenceLint
      description: dummy response to silence lint errors in this file
      tags:
        - Schema Definitions
      responses:
        "200":
          description: dummy response to silence lint errors in this file
          content:
              application/json:
                schema:
                  additionalProperties: false
                  oneOf:
                    - $ref: "#/components/schemas/password"
                    - $ref: "#/components/schemas/ip4"
                    - $ref: "#/components/schemas/ip6"
                    - $ref: "#/components/schemas/cidr4"
                    - $ref: "#/components/schemas/cidr6"
                    - $ref: "#/components/schemas/mac"
                    - $ref: "#/components/schemas/uuid"
                    - $ref: "#/components/schemas/url"
                    - $ref: "#/components/schemas/url-http-s"
                    - $ref: "#/components/schemas/url-absolute"
                    - $ref: "#/components/schemas/activation-code"
                    - $ref: "#/components/schemas/adapter-type"
                    - $ref: "#/components/schemas/epoch-timestamp"
                    - $ref: "#/components/schemas/iso3166-country"
                    - $ref: "#/components/schemas/iana-timezone"
                    - $ref: "#/components/schemas/ph2-bearer-token"
                    - $ref: "#/components/schemas/adapter-name"
                    - $ref: "#/components/schemas/email-address"
                    - $ref: "#/components/schemas/admin-as-email-address"

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

tags:
  - name: Schema Definitions
    description: These are all schema definitions.

#########################################################
# Components are preformatted data that can be reused in definitions.
components:

  securitySchemes:
    $ref: "../PHMothership.openapi.yml#/components/securitySchemes"

  schemas:

    password:
      type: string
      format: password
      minLength: 8
      maxLength: 64
      example: "my p455w0rd"
      pattern: "^[\u0020-\u007e]*$"


    # IP4 IP Address
    ip4:
      type: string
      format: IPv4 Address
      pattern: "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"
      minLength: 7
      maxLength: 15
      description: |-
        An IP4 formatted IP Address
      example: "192.168.0.55"

    # IP6 IP Address
    ip6:
      type: string
      format: IPv6 Address
      pattern: "^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))$"
      minLength: 3
      maxLength: 45
      description: |-
        An IP6 formatted IP Address
      example: "2001:db8:85a3::8a2e:370:7334"

    # IP4 CIDR
    cidr4:
      type: string
      format: IPv4 CIDR
      pattern: "^([0-9]{1,3}\\.){3}[0-9]{1,3}(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
      minLength: 9
      maxLength: 18
      description: |-
        An IP4 CIDR
      example: "192.168.0.0/24"

    # IP6 CIDR
    cidr6:
      type: string
      format: IPv6 CIDR
      pattern: "^s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:)))(%.+)?s*(\\/([0-9]|[1-9][0-9]|1[0-1][0-9]|12[0-8]))?$"
      minLength: 4
      maxLength: 43
      description: |-
        An IP6 CIDR
      example: "fe80::0204:61ff:fe9d:f156/127"

    # EUI-48 MAC Address
    mac:
      type: string
      format: EUI-48
      pattern: "^([0-9a-fA-F]{2}([:-]))(([0-9a-fA-F]{2})\\2){4}([0-9a-fA-F]{2})$"
      maxLength: 17
      minLength: 17
      description: |-
        An EUI-48 formatted mac address.
      example: "00-00-5E-DF-98-EB"

    # Universally Unique ID
    uuid:
      type: string
      format: UUID
      description: |-
        Unique Identifier
      maxLength: 36
      minLength: 36
      pattern: "^[0-9a-fA-F]{8}(-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}$"
      example: "cd73b915-89a4-4971-9d86-bce91786b12a"

    url:
      type: string
      format: "URL"
      minLength: 1
      maxLength: 2000
      nullable: true
      pattern: "^(?:(?:https:\\/\\/)|(?:\\./))?[\\w.-]+(?:\\.[\\w\\.-]+)+[\\w\\-\\._~:/?#[\\]@!\\$&'\\(\\)\\*\\+,;=.]+$"
      description: |-
        A URL","including relative references.  Will only accept https
        relative urls.
      example: "./relative.url"

    url-http-s:
      type: string
      format: "URL"
      minLength: 1
      maxLength: 2000
      nullable: true
      pattern: "^(?:(?:http(s)?:\\/\\/)|(?:\\./))?[\\w.-]+(?:\\.[\\w\\.-]+)+[\\w\\-\\._~:/?#[\\]@!\\$&'\\(\\)\\*\\+,;=.]+$"
      description: |-
        A URL","including relative references.  Will accept http/https and
        relative urls.
      example: "./relative.url"

    url-absolute:
      type: string
      format: "URL"
      minLength: 1
      maxLength: 2000
      nullable: true
      pattern: "^(?:https:\\/\\/)?[\\w.-]+(?:\\.[\\w\\.-]+)+[\\w\\-\\._~:/?#[\\]@!\\$&'\\(\\)\\*\\+,;=.]+$"
      description: |-
        An Absolute URL.  Will only accept https as protocol.
      example: "https://absolute.url"

    # Adapter Activation Code
    activation-code:
      type: string
      pattern: "^....-....$"
      minLength: 9
      maxLength: 9
      description: |-
        Adapter/Router activation code. Note: pattern and length are
        placeholders until the format is finalized.
      example: "????-????"

    # Type of Adapter
    adapter-type:
      type: string
      enum:
        - "Router-V1"
      description: |-
        The hardware type of the adapter/router.

    # Epoch Timestamp
    epoch-timestamp:
      type: integer
      format: int64
      minimum: 1587732975
      maximum: 4743406575
      nullable: true
      description: |-
        A Time","expressed as seconds since Jan 01 1970. (UTC). **NULL** = unknown
      example: 1587732975

    # ISO 3166 Country Codes
    iso3166-country:
      type: string
      format: ISO3166 Code
      #pattern: "^[A-Z][A-Z]$"
      example: "US"
      #minLength: 2
      #maxLength: 2
      enum:
        ["AF","AX","AL","DZ","AS","AD","AO","AI","AQ","AG","AR","AM","AW","AU","AT","AZ","BS","BH",
        "BD","BB","BY","BE","BZ","BJ","BM","BT","BO","BQ","BA","BW","BV","BR","IO","BN","BG",
        "BF","BI","CV","KH","CM","CA","KY","CF","TD","CL","CN","CX","CC","CO","KM","CG","CD","CK",
        "CR","CI","HR","CU","CW","CY","CZ","DK","DJ","DM","DO","EC","EG","SV","GQ","ER","EE","SZ",
        "ET","FK","FO","FJ","FI","FR","GF","PF","TF","GA","GM","GE","DE","GH","GI","GR","GL","GD",
        "GP","GU","GT","GG","GN","GW","GY","HT","HM","VA","HN","HK","HU","IS","IN","ID","IR","IQ",
        "IE","IM","IL","IT","JM","JP","JE","JO","KZ","KE","KI","KP","KR","KW","KG","LA","LV","LB",
        "LS","LR","LY","LI","LT","LU","MO","MG","MW","MY","MV","ML","MT","MH","MQ","MR","MU","YT",
        "MX","FM","MD","MC","MN","ME","MS","MA","MZ","MM","NA","NR","NP","NL","NC","NZ","NI","NE",
        "NG","NU","NF","MK","MP","NO","OM","PK","PW","PS","PA","PG","PY","PE","PH","PN","PL","PT",
        "PR","QA","RE","RO","RU","RW","BL","SH","KN","LC","MF","PM","VC","WS","SM","ST","SA","SN",
        "RS","SC","SL","SG","SX","SK","SI","SB","SO","ZA","GS","SS","ES","LK","SD","SR","SJ","SE",
        "CH","SY","TW","TJ","TZ","TH","TL","TG","TK","TO","TT","TN","TR","TM","TC","TV","UG","UA",
        "AE","GB","US","UM","UY","UZ","VU","VE","VN","VG","VI","WF","EH","YE","ZM","ZW"]
      description: |-
        an ISO3166 country code

    # Timezone as specified by the IANA TZ Database
    iana-timezone:
      type: string
      format: IANA Timezone
      description: IANA Timezone name.
      minLength: 3
      maxLength: 44
      pattern: ^([A-Za-z-_]){1,14}\/([A-Za-z-_]){1,14}(\/([A-Za-z-_]){1,14})?$
      default: "Etc/UTC"
      example: "America/Chicago"

    ph2-bearer-token:
      type: string
      format: JWT
      description: Privacy Hero 2 API Bearer Token (Based on JWT)
      minLength: 64
      maxLength: 1024 # TODO: Calculate true minimum and maximum length
      pattern: "^([A-Za-z0-9-_])+\\.([A-Za-z0-9-_])+(\\.[A-Za-z0-9-_]+)?$"
      example: "AeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1MTYyMzkwMjJ9AB"

    adapter-name:
      type: string
      format: text
      nullable: true
      description: The name of an adapter.
      minLength: 0
      maxLength: 64
      pattern: "^[\\w\\W]+$"
      example: "Home Office Adapter"

    email-address:
      type: string
      format: email
      minLength: 6 # len("a@b.cd")
      maxLength: 320 # RFC3696
      pattern: "(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\\\x01-\\\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])"
      example: "example@email.com"
      description: An email address

    admin-as-email-address:
      type: string
      format: admin:client email
      minLength: 6 # len("a@b.cd")
      maxLength: 320 # RFC3696
      pattern: "(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\\\x01-\\\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\]):(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\\\x01-\\\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]\\:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])"
      example: "admin@privacyhero.com:example@email.com"
      description: An email address