openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /client/notify"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    Set the notification settings for a particular client.

    `/client/notify`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PH2-API.oas3.yml#/components/securitySchemes"

tags:
  - name: Client Management
    description: Operations related to Client Management

paths:
  /client/notify:
    post:
      operationId: clientNotify
      tags:
        - Client Management
      summary: Subscribe/Unsubscribe to notifications.
      description: |-
        # Usage
        Allows the client to subscribe/unsubscribe web push notifications.

        Push notifications require the client to authorize the subscription.
        The App is responsible for getting the clients authority with the
        relevant service, and then passing the WebPush Client Token (AKA
        "Registration Id") to the Backend API.  Anytime the WebPush Client Token
        is renewed by the Client, this same call is made to update it.

        ## Parameters
          - **token**: the WebPush Client Token obtained when the client
          consented to receiving notifications.
          - **service**: the WebPush Service being employed by the clients
          application.
            - **"FIREBASE"** is used for Android and non-safari web push
            notifications.
            - **"APNS-IOS"** is used for IOS Apps.
            - **"APNS-WEB"** is used for Safari Web Push notifications.
          - **cancel**: Optional.  Set to True, to cancel notifications for the service.
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - token
                - service
              additionalProperties: false
              properties:
                token:
                  type: string
                  format: WebPush Client Token
                  pattern: "^[\\w]+$"
                  minLength: 8
                  maxLength: 256 # TODO: Find out the true range of token sizes.
                  example: "f1R3Rk5uTiIvC1prMTr7ue:APA91bGPPasEn7wqi2ZnArJsXKlbk9OCZ6jweCsWVPXA"
                  description: |-
                    The clients notification token for their service.  Also known as the
                    "Registration Id".
                service:
                  type: string
                  format: Notification
                  enum:
                    - "FIREBASE"
                    - "APNS-IOS"
                    - "APNS-WEB"
                  example: "FIREBASE"
                  description: |-
                    The service the client token relates to.
                cancel:
                  type: boolean
                  default: false
                  example: true
                  description: |-
                    IF true, the notifications attached to this token are canceled.

      responses:
        "200":
          description: |-
            Success, Notification set.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Ack"
              example:
                msg: "Notification Registered OK."

        "400":
          description: |-
            General Request processing error.  Possible errors are:
            * `"Internal Server Error."` - Fatal uncategorized error in server.
            * `"Required Parameters missing or malformed."` - JSON Message Body
            Error.
            * `"Invalid Service"` - Password failed security strength check.
            * `"Invalid WebPush Token"` - Token is not valid.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Internal Server Error."

        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "415":
          $ref: "../../inc/response.oas3.yml#/components/responses/415"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        default:
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
