openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /profile/cfg/name"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    Create a user profile.

    `/profile/cfg/name`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PH2-API.oas3.yml#/components/securitySchemes"

tags:
  - name: Profile Management
    description: Operations related to Profile Management

paths:
  /profile/cfg/bedtimes:
    post:
      operationId: profileCfgBedtimes
      tags:
        - Profile Management
      summary: Set the weekly bedtimes for a profile.
      description: |-
        # Usage

        Allows the weekly bedtimes to be set for a profile.  The entire weekly
        schedule is always set, if some entries do not change, simply send them
        as configured.

        ## Security Requirements
          - **appKey** **MUST NOT** be present in the call.
          - **clientToken** **MUST** be present, not in need of renewal and valid.

        ## Parameters
          - **id**: The unique id of the profile.
          - **bedtime**: An array of bedtimes to set for the profile.

      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - id
                - bedtime
              additionalProperties: false
              properties:
                id:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
                bedtime:
                  $ref: "../../inc/profile.oas3.yml#/components/schemas/Bedtimes"
              example:
                id: "cd73b915-89a4-4971-9d86-bce91786b12a"
                bedtime: [
                    {
                      "start-time": 77400,
                      "duration": 37800
                    },
                    {
                      "start-time": 77400,
                      "duration": 37800
                    },
                    {
                      "start-time": 77400,
                      "duration": 37800
                    },
                    {
                      "start-time": 77400,
                      "duration": 37800
                    },
                    {
                      "start-time": 77400,
                      "duration": 37800
                    },
                    {
                      "start-time": 82800,
                      "duration": 25200
                    },
                    {
                      "start-time": 82800,
                      "duration": 25200
                    }
                  ]

      responses:
        "200":
          description: |-
            Success, The profile bedtime settings were made.
          content:
            application/json:
              schema:
                $ref: "../../inc/profile.oas3.yml#/components/schemas/Profile"
              example: {
                "id": "cd73b915-89a4-4971-9d86-bce91786b12a",
                "adapter": "d46cb964-4a40-43ac-87f6-cdefa19fa121",
                "name": "Rugrats",
                "icon": "rugrats.ico",
                "datausage": {
                  "tx": 1234567,
                  "rx": 1234613450
                },
                "settings": {
                  "youtube-restricted": false,
                  "safesearch": false,
                  "internet-pause": null,
                  "bedtime": [
                    {
                      "start-time": 77400,
                      "duration": 37800
                    },
                    {
                      "start-time": 77400,
                      "duration": 37800
                    },
                    {
                      "start-time": 77400,
                      "duration": 37800
                    },
                    {
                      "start-time": 77400,
                      "duration": 37800
                    },
                    {
                      "start-time": 77400,
                      "duration": 37800
                    },
                    {
                      "start-time": 82800,
                      "duration": 25200
                    },
                    {
                      "start-time": 82800,
                      "duration": 25200
                    }
                  ],
                  "bedtime-delay": 0
                }
              }

        "400":
          description: |-
            General Request processing error.  Possible errors are:
            * `"Internal Server Error."` - Fatal uncategorized error in server.
            * `"Required Parameters missing or malformed."` - JSON Message Body
            Error.
            * `"Profile Name not unique."` - The Profile Name is not unique.
            * `"Profile Name reserved."` - The Profile Name is reserved.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Internal Server Error."
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "404":
          $ref: "../../inc/response.oas3.yml#/components/responses/404"
        "415":
          $ref: "../../inc/response.oas3.yml#/components/responses/415"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        "default":
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
