openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /profile/cfg/name"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    Create a user profile.

    `/profile/cfg/name`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PH2-API.oas3.yml#/components/securitySchemes"

tags:
  - name: Profile Management
    description: Operations related to Profile Management

paths:
  /profile/cfg/bedtimes:
    post:
      operationId: profileCfgBedtimes
      tags:
        - Profile Management
      summary: Set the weekly bedtimes for a profile.
      description: |-
        # Usage

        Allows the Start time for "Bedtime" to be set independently for "School
        Nights" and "Other Nights".  The duration of a "Bedtime" is system
        controlled.  School Nights are the nights BEFORE a school day.  So, in
        the typical school system where a school day is Monday to Friday, school
        nights are Sunday thru Thursday.

        ## Parameters
          - **id**: The unique id of the profile.
          - **school**: The time in minutes from midnight when bedtime
          starts on a "school night".  Set to -1 if it is disabled.
          - **other**: The time in minutes from midnight when bedtime
          starts on nights other than school nights.  Set to -1 if it is
          disabled.
          - **school-nights**: An array of booleans which sets which nights of the
          week are school nights.  The First entry is Monday, the last is
          Sunday.  true = This is a school night.  false = It is not a school night.

      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - id
                - enabled
                - school
                - other
                - school-nights
              additionalProperties: false
              properties:
                id:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
                enabled:
                  type: boolean
                  default: false
                  description: Enable the bedtime function (true) or not (false)
                school:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/time-of-day-mins"
                other:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/time-of-day-mins"
                school-nights:
                  $ref: "../../inc/profile.oas3.yml#/components/schemas/school-nights"
              example:
                id: "cd73b915-89a4-4971-9d86-bce91786b12a"
                enabled: true
                school: 1260
                other: 1350
                school-nights:
                  - true
                  - true
                  - true
                  - true
                  - false
                  - false
                  - true

      responses:
        "200":
          description: |-
            Success, The profile bedtime settings were made.
          content:
            application/json:
              schema:
                $ref: "../../inc/profile.oas3.yml#/components/schemas/ProfileCfgPending"
              example:
                id: "cd73b915-89a4-4971-9d86-bce91786b12a"
                adapter: "d46cb964-4a40-43ac-87f6-cdefa19fa121"
                name: "Rugrats"
                icon: "rugrats.ico"
                settings:
                  youtube-restricted: false
                  safesearch: false
                  internet-pause: null
                  bedtime:
                    school-time: 1290
                    other-time: -1
                    school-nights:
                      - true
                      - true
                      - true
                      - true
                      - false
                      - false
                      - true
                  bedtime-delay: 45
                since: 1604896473
                pending: 1604897123

        "400":
          description: |-
            General Request processing error.  Possible errors are:
            * `"Internal Server Error."` - Fatal uncategorized error in server.
            * `"Required Parameters missing or malformed."` - JSON Message Body
            Error.
            * `"Profile Name not unique."` - The Profile Name is not unique.
            * `"Profile Name reserved."` - The Profile Name is reserved.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Internal Server Error."
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "404":
          $ref: "../../inc/response.oas3.yml#/components/responses/404"
        "415":
          $ref: "../../inc/response.oas3.yml#/components/responses/415"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        "default":
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
