openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /profile/list"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    List all profiles created for the account.

    **_EARLY DRAFT_**

    `/profile/list`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PHMothership.openapi.yml#/components/securitySchemes"

tags:
  - name: Profile Management
    description: Operations related to Profile Management

paths:
  /profile/list:
    get:
      operationId: profileList
      tags:
        - Profile Management
      summary: Lists all/selected profiles created by the client on their account.
      description: |-
        Generates a list of all profiles associated with the clients account.

        **_EARLY DRAFT_**
      security:
        - clientToken: []

      parameters:
        - in: query
          name: profile
          schema:
            type: string
            default: null
            nullable: true
          example: "shared"
          description: |-
            If specified, the profile list returned in the response will be
            restricted to this single profile.
        - in: query
          name: devices
          schema:
            type: boolean
            default: false
          example: true
          description: |-
            If devices is not present, or false, then the response will just
            list the known profiles.  If it is true, the list will include every
            device linked to the profiles.

      responses:
        "200":
          description: |-
            Success, The claimed adapters details.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "../../inc/profile.oas3.yml#/components/schemas/Profiles"
                  - $ref: "../../inc/profile.oas3.yml#/components/schemas/ProfilesDevices"

        "400":
          description: |-
            General Request processing error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Could not claim the adapter!"

        "403":
          description: |-
            Invalid Client Token, could not authorize api access.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/GW_NegAuth"

        "500":
          description: |-
            An Internal server error occurred.  Operation failed.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/GW_InternalError"
