openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /profile/usage"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    Generate a data usage report for all device on a profile.

    `/profile/usage`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PH2-API.oas3.yml#/components/securitySchemes"

tags:
  - name: Profile Management
    description: Operations related to Profile Management

paths:
  /profile/usage:
    get:
      operationId: profileUsage
      tags:
        - Profile Management
      summary: Get profile data usage.
      description: |-
        # Usage

        Generates a list of data usage values for a profile, at a specified
        resolution.  Profile usage is a synthetic aggregate of all device usage,
        so, for example, if a high volume device is moved between profiles, the
        old profiles usage will decrease by the devices usage, and the new profile
        of the device will increase its usage by the same amount.

        ## Parameters
          - **id**: The Unique profile ID.

      parameters:
        - in: query
          name: id
          required: true
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
          description: |-
            The unique profile id.
        - in: query
          name: resolution
          schema:
            type: string
            enum:
              - "Hourly"
              - "Daily"
              - "Weekly"
              - "Monthly"
            default: "Hourly"
          description: |-
            The time resolution to report. Hourly is hourly, Daily is 24 hours.
            Weekly is 7 days and Monthly is the full month aligned to the
            billing period.  If not specified the resolution is "Hourly".

        - in: query
          name: start
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/epoch-timestamp"
          description: |-
            The start of the reporting window.  If not specified, defaults to
            the oldest data on record for the device.

        - in: query
          name: end
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/epoch-timestamp"
          description: |-
            The end of the reporting window.  If not specified, defaults to
            now.


      responses:
        "200":
          description: |-
            Success, The profile data usage is returned.
          content:
            application/json:
              schema:
                $ref: "../../inc/device.oas3.yml#/components/schemas/DeviceUsageHistory"

        "400":
          description: |-
            General Request processing error.  Possible errors are:
            * `"Internal Server Error."` - Fatal uncategorized error in server.
            * `"Required Parameters missing or malformed."` - JSON Message Body
            Error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Internal Server Error."
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "404":
          $ref: "../../inc/response.oas3.yml#/components/responses/404"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        "default":
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
