openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /auth/chgemail"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    `/auth/chgemail`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

tags:
  - name: Account Management
    description: Operations related to Account Creation and Management

components:
  securitySchemes:
    $ref: "../../PH2-API.oas3.yml#/components/securitySchemes"

paths:
  /auth/chgemail:
    post:
      operationId: changeEmail
      tags:
        - Account Management
      summary: Change a Clients Email Address.
      description: |-
        # Usage

        Causes the Clients Email Address to be changed.
        Will also cause an email to be sent to both the
        old email address, advising the client it is being changed.
        AND, to the new email address to confirm the address is valid.

        The Confirmation Email contains the callback as an embedded link which
        will call back into the initiating application.

        The URL passed as the callback must be able to accept three parameter in
        the url of the form:
        ```
        callback.url/path?verify=<token>&pw=<false/true>&exp=<time>
        ```
         - **verify** is the verification token to be sent back to the API server by
            the app on the **/v1/auth/confirmcustomer** call.
         - **pwd** specifies that a confirmation password must be prompted from
            the Client, and supplied to the API in the **/v1/auth/confirmcustomer**
            call.
         - **exp** specifies when the verification token will expire.  Any call
            to **/v1/auth/confirmcustomer**` after this time will fail.

        ## Parameters
          - **email**: The new email address to change to.
          - **callback**: The complete URL, minus parameters, which is embedded in
          the email sent to the customer to confirm their account creation. It
          must point to the app which instigated this request.

      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - email
                - callback
              additionalProperties: false
              properties:
                email:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/email-address"
                callback:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/url-callback"
            example:
              email: "newemail@email.org"
              callback: "https://www.myapp.url/callback"

      responses:
        "200":
          description: |-
            The email change was initiated.  Confirmation Emails sent.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Ack"
              example:
                msg: "Emails sent to user, OK."

        "400":
          description: |-
            The Email address is already in use by another Client.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Email address already used by another account."
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "415":
          $ref: "../../inc/response.oas3.yml#/components/responses/415"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        default:
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
