openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /auth/chgpwd"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    `/auth/chgpwd`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

components:
  securitySchemes:
    $ref: "../../PHMothership.openapi.yml#/components/securitySchemes"

paths:
  /auth/chgpwd:
    post:
      operationId: changePassword
      tags:
        - Account Management
      summary: Change a Clients password.
      description: |-
        Causes the Clients password to be changed.
      security:
        - clientToken: []

      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - old
                - new
              properties:
                old:
                  type: string
                  format: password
                  description: |-
                    The old password of the Client.
                new:
                  type: string
                  format: password
                  description: |-
                    The new password of the Client.

      responses:
        "200":
          description: |-
            The password was changed OK.
          content:
            application/json:
              schema:
                $ref: "../../inc/components.oas3.yml#/components/schemas/Authorized"

        "400":
          description: |-
            The new password is not secure enough.
          content:
            application/json:
              schema:
                $ref: "../../inc/components.oas3.yml#/components/schemas/Nack"
              example:
                error: |-
                  Password must contain at least One UpperCase character, One
                  LowerCase character, One Number and be at least 8 characters
                  long.

        "401":
          description: |-
            The Clients Bearer Token is invalid or not recognized.
          headers:
            WWW-Authenticate:
              schema:
                type: string
                example: Bearer realm=privacyhero2.api.com
                description: |-
                  indicates the authentication scheme(s) and parameters
                  applicable to the target resource.

        "403":
          description: |-
            The Clients Old Password does not match, can not change.
          content:
            application/json:
              schema:
                $ref: "../../inc/components.oas3.yml#/components/schemas/Nack"
              example:
                error: "OLD Password Invalid."
