openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /auth/chgpwd"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    `/auth/chgpwd`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PH2-API.oas3.yml#/components/securitySchemes"

tags:
  - name: Account Management
    description: Operations related to Account Creation and Management

paths:
  /auth/chgpwd:
    post:
      operationId: changePassword
      tags:
        - Account Management
      summary: Change a Clients password.
      description: |-
        # Usage
        Causes the Clients password to be changed.

        ## Parameters
          - **old**: The old password of the Client.  Must be Valid.
          - **new**: The new password of the Client.
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - old
                - new
              additionalProperties: false
              properties:
                old:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/password"
                new:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/password"
              example:
                old: "4n 0ld p455w0rd"
                new: "my n3w p455w0rd"

      responses:
        "200":
          description: |-
            The password was changed OK.
          content:
            application/json:
              schema:
                $ref: "../../inc/auth.oas3.yml#/components/schemas/Authorized"

        "400":
          description: |-
            General Request processing error.  Possible errors are:
            * `"Internal Server Error."` - Fatal uncategorized error in server.
            * `"Required Parameters missing or malformed."` - JSON Message Body
            Error.
            * `"Insecure Password"` - Password failed security strength check.
            * `"Old Password doesn't match"` - Old Password failed security check.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Internal Server Error."

        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "415":
          $ref: "../../inc/response.oas3.yml#/components/responses/415"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        default:
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
