openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /auth/delcustomer"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    `/auth/delcustomer`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PHMothership.openapi.yml#/components/securitySchemes"

tags:
  - name: Account Management
    description: Operations related to Account Creation and Management

paths:
  /auth/delcustomer:
    post:
      operationId: deleteCustomer
      tags:
        - Account Management
      summary: Delete a Customer Account.
      description: |-
        Causes an email to be sent to the customer requiring them
        to confirm they wish to mark the account for deletion.

        The Email contains the callback as an embedded link which
        will call back into the initiating application.
      security:
        - clientToken: []
          appKey: []

      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              properties:
                password:
                  type: string
                  format: password
                  description: |-
                    The clients password, if they have one.
                callback:
                  type: string
                  format: url
                  example: "https://www.myapp.url/callback"
                  description: |-
                    The complete URL, minus parameters, which is embedded in the
                    email sent to the customer to confirm their account
                    creation. It must point to the app which instigated this
                    request.

      responses:
        "200":
          description: |-
            Confirmation Email sent.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Ack"
              example:
                msg: "Email sent to user, OK."

        "400":
          description: |-
            The Password supplied does not match the Customers known password.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Invalid Password."

        "401":
          description: |-
            The Clients Bearer Token is invalid or not recognized.
          headers:
            WWW-Authenticate:
              schema:
                type: string
                example: Bearer realm=privacyhero2.api.com
                description: |-
                  indicates the authentication scheme(s) and parameters
                  applicable to the target resource.

        "403":
          description: |-
            The App Token is invalid.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Application Token Invalid."
