openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - Email Callback"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    Format of the Email Callback URL.
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

servers:
  - url: localhost
    description: the callback is a local callback to the app.

tags:
  - name: Account Management
    description: Operations related to Account Creation and Management

paths:
  /callback:
    get:
      operationId: appCallback
      tags:
        - Account Management
      summary: Callback to App that requested a New Customer.
      description: |-
        This is the format of the callback that will be presented to the
        customer in their confirmation email.

        It is linked to the instigating App, so that the App can continue
        the process of creating the new account, resetting the password,
        re-establishing credentials, etc .
      servers:
        - url: ph2app://android.app/some/path
          description: |-
            The link which can open the app which called
            **v1//auth/newcustomer**, etc.

      parameters:
        - in: query
          name: verify
          required: true
          schema:
            type: string
            format: token
            pattern: "^[A-Za-z0-9-_]+\\.[A-Za-z0-9-_]+$"
            minLength: 64
            maxLength: 1000
            example: "abcdefghijklmnopqrstuzwxyz12345.67890ABCDEFGHIJKMLNOPQRSTUVWXYZa"
          description: The New Customer confirmation token.
        - in: query
          name: exp
          required: true
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/epoch-timestamp"
          description: |-
            The Time, after which the verification token will become invalid.

        - in: query
          name: pw
          schema:
            type: boolean
            default: true
          description: |-
            If true, the user must be prompted to create a password and the
            password must be sent in the `confirmcustomer` API call.
            If it is not present, it defaults to `true`
      security: []

      responses:
        "200":
          description: |-
            The message was accepted.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Ack"

        "400":
          description: |-
            The token expired before the link was used.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        default:
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
