openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - Email Callback"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    Format of the Email Callback URL.
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

servers:
  - url: localhost
    description: the callback is a local callback to the app.

tags:
  - name: Account Management
    description: Operations related to Account Creation and Management

paths:
  /callback:
    get:
      operationId: appCallback
      tags:
        - Account Management
      summary: Callback to App that requested a New Customer.
      description: |-
        # Usage
        This is the format of the callback that will be presented to the
        customer in their confirmation email.

        It is linked to the instigating App, so that the App can continue
        the process of creating the new account, resetting the password,
        re-establishing credentials, etc .

        ## Security Requirements

        There are no specific security requirements.  However the token is
        cryptographically signed, and only valid for the specified duration.
        The application only needs to check the duration in the call, the API
        server will verify the token remains valid and is properly formed when
        the token is presented.

        ## Parameters
         - **verify** is the verification token to be sent back to the API server by
            the app on the **/v1/auth/confirmcustomer** call.
         - **pwd** specifies that a confirmation password must be prompted from
            the Client, and supplied to the API in the **/v1/auth/confirmcustomer**
            call.
         - **exp** specifies when the verification token will expire.  Any call
            to **/v1/auth/confirmcustomer**` after this time will fail.

      servers:
        - url: ph2app://android.app/some/path
          description: |-
            The link which can open the app which called
            **v1//auth/newcustomer**, etc.

      parameters:
        - in: query
          name: verify
          required: true
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/ph2-bearer-token"
          description: The New Customer confirmation token.
          example: "AeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1MTYyMzkwMjJ9AB"
        - in: query
          name: exp
          required: true
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/epoch-timestamp"
          description: |-
            The Time, after which the verification token will become invalid.
          example: 1587759975
        - in: query
          name: pwd
          schema:
            type: boolean
            default: true
            example: false
          description: |-
            If true, the user must be prompted to create a password and the
            password must be sent in the `confirmcustomer` API call.
            If it is not present, it defaults to `true`
      security: []

      responses:
        "200":
          description: |-
            The message was accepted.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Ack"

        "400":
          description: |-
            The token expired before the link was used.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        default:
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
