openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /auth/login"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    `/auth/login`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PH2-API.oas3.yml#/components/securitySchemes"

tags:
  - name: Account Management
    description: Operations related to Account Creation and Management

paths:
  "/auth/login":
    post:
      operationId: login
      tags:
        - Account Management
      summary: Log a Client in to their account.
      description: |-
        # Usage
        Logs a client/admin in to their account, by validating their credentials
        and returning a Bearer token for API access.  Can also be used by an
        admin to impersonate the login of a client.

        This API call is only made for applications that use a password for
        authorization validation.  Other applications need to do account
        recovery if the access token is lost or expired.

        ## Security Requirements
          For a normal client/admin login, the Authorization Bearer token sent
          to authenticate for this message is the Application unique and
          pre-distributed App Token.

          However, if the client is an Admin user, this message can be called to
          impersonate a non admin client.  In this case the Authorization Bearer
          token must be the Admins Authorization Bearer token AND the password
          in the message must be the Administrators password.

        ## Parameters
          - **id**: The clients ID,  different clients will present different ID.
            - Customer: Their email address
            - Admin: Their email address
            - Impersonation: The email address of the client the administrator
            wishes to impersonate.
          - **pwd**: The shared secret used to identify the client.  This is the
          Clients or Administrators password.  However, in the case of
          Impersonation, this password MUST be the administrators password and
          it must match the administrator identified by their Authorization
          Bearer Token.  It is sent unencrypted/unhashed because the link is
          protected from eaves dropping with https.  Admins can ONLY log in
          through this call.
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              additionalProperties: false
              required:
                - id
                - pwd
              properties:
                id:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/email-address"
                pwd:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/password"
            examples:
              client:
                value:
                  id: "client@email.com"
                  pwd: "123456789"
                description: An Example Client login
              admin:
                value:
                  id: "admin@privacyhero.com"
                  pwd: "iNBi5tRE"
                description: An Example Admin login
              impersonation:
                value:
                  id: "client@email.com"
                  pwd: "iNBi5tRE"
                description: An Example Impersonated login

      responses:
        "200":
          description: |-
            The message was accepted, and the account has been logged in.
          content:
            application/json:
              schema:
                $ref: "../../inc/auth.oas3.yml#/components/schemas/Authorized"
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401-appKey"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403-appKey"
        "415":
          $ref: "../../inc/response.oas3.yml#/components/responses/415"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        default:
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
