openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /auth/renew"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    `/auth/renew`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

components:
  securitySchemes:
    $ref: "../../inc/components.yml#/components/securitySchemes"

paths:
  "/auth/renew":
    get:
      operationId: authRenew
      tags:
        - Account Management
      summary: Renew a Client Authorization Token.
      description: |-
        Causes the Authorization token attached to the API call
        to be renewed, and a new token returned.
      security:
        - clientToken: []

      responses:
        "200":
          description: |-
            The message was accepted, and the token has been renewed.
          content:
            application/json:
              schema:
                $ref: "../../inc/components.yml#/components/schemas/Authorized"
        "401":
          description: |-
            The Clients Bearer Token is invalid or not recognized.
          headers:
            WWW-Authenticate:
              schema:
                type: string
                example: Bearer realm=privacyhero2.api.com
                description: |-
                  indicates the authentication scheme(s) and parameters
                  applicable to the target resource.

        "403":
          description: |-
            The Clients Bearer token is valid, but its time to be renewed has
            passed.  The Client must be re-authenticated.
          content:
            application/json:
              schema:
                $ref: "../../inc/components.yml#/components/schemas/Nack"
              example:
                error: "API Token has expired."
