openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /device/assign"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    Assign a device to a profile.

    `/device/assign`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PH2-API.oas3.yml#/components/securitySchemes"

tags:
  - name: Device Management
    description: Operations related to Device Management

paths:
  /device/assign:
    post:
      operationId: deviceAssign
      tags:
        - Device Management
      summary: Assign a device to a Profile.
      description: |-
        # Usage

        Assigns a device to a profile.  Can only assign devices to profiles that
        exist associated with the same adapter.

        ## Parameters
          - **id**: The unique id of the device we are associating with the profile.
          - **profile**: The unique id of the profile we are assigning the
          device to.

      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - id
                - profile
              additionalProperties: false
              properties:
                id:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
                profile:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
              example:
                id: "d46cb964-4a40-43ac-87f6-cdefa19fa121"
                profile: "66f7346a-48af-4614-bd7b-6c17093d75e3"

      responses:
        "200":
          description: |-
            Success, The device was assigned to the profile.
          content:
            application/json:
              schema:
                $ref: "../../inc/device.oas3.yml#/components/schemas/Device"

        "400":
          description: |-
            General Request processing error.  Possible errors are:
            * `"Internal Server Error."` - Fatal uncategorized error in server.
            * `"Required Parameters missing or malformed."` - JSON Message Body
            Error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Internal Server Error."
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "404":
          $ref: "../../inc/response.oas3.yml#/components/responses/404"
        "415":
          $ref: "../../inc/response.oas3.yml#/components/responses/415"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        "default":
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
