openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /device/list"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    List all adapters on an account.

    **_EARLY DRAFT_**

    `/device/list`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PHMothership.openapi.yml#/components/securitySchemes"

tags:
  - name: Device Management
    description: Operations related to Device Management

paths:
  /device/list:
    get:
      operationId: deviceList
      tags:
        - Device Management
      summary: Lists all devices and their associated Adapter/Profile.
      description: |-
        Generates a list of all devices.

        **_EARLY DRAFT_**
      security:
        - clientToken: []

      parameters:
        - in: query
          name: mac
          schema:
            type: string
            nullable: true
          example: "00-00-5E-32-5C-DE"
          description: |-
            If specified will only return details of the listed device mac address.

      responses:
        "200":
          description: |-
            Success, The claimed adapters details.
          content:
            application/json:
              schema:
                $ref: "../../inc/device.oas3.yml#/components/schemas/Devices"

        "400":
          description: |-
            General Request processing error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Could not claim the adapter!"
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
