openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /adapter/datacap"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    Set the Datacap for a particular Adapter.

    `/adapter/name`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PH2-API.oas3.yml#/components/securitySchemes"

tags:
  - name: Adapter Management
    description: Operations related to Adapter Management

paths:
  /adapter/cfg/datacap:
    post:
      operationId: adapterDataCap
      tags:
        - Adapter Management
      summary: Set the datacap for a particular adapter.
      description: |-
        # Usage
        Sets the data caps for the identified adapter.  Data Cap is used to
        check if monthly usage will exceed the data cap for reporting and
        notification purposes.

        ## Parameters
          - **id**: The Adapters ID to set the data cap for.
          - **cap**: The datacap for the adapter.  This is the total number of
          MB the customer may use in their internet plane before extra charges
          are levied, or speed slows down (depending on the ISP and Plan).  It
          is a combined value, representing both the data TX and RX.
          - **day**: The day in the month when the datacap resets. 1 == data cap
          resets on the 1st day of the month. If the day is greater than the
          days in the current month, it is assumed the datacap resets at the
          start of the last day of the month.  Even if **cap** is set to zero,
          the **day** must be set between 1 and 31 as it marks the first day of
          the clients monthly billing cycle.
      requestBody:
        required: true
        description: "The DataCap settings to apply."
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - cap
                - day
              additionalProperties: false
              properties:
                id:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
                cap:
                  $ref: "../../inc/adapter.oas3.yml#/components/schemas/datacap"
                day:
                  $ref: "../../inc/adapter.oas3.yml#/components/schemas/datacap-reset"

      responses:
        "200":
          description: |-
            Success, Adapter datacap set.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Ack"
              example:
                msg: "Success, Adapter datacap set."
        "400":
          description: |-
            General Request processing error.  Possible errors are:
            * `"Internal Server Error."` - Fatal uncategorized error in server.
            * `"Required Parameters missing or malformed."` - JSON Message Body
            Error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Internal Server Error."
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "415":
          $ref: "../../inc/response.oas3.yml#/components/responses/415"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        default:
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
