openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /adapter/claim"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    Claim an Adapter for a client account.

    `/adapter/claim`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PH2-API.oas3.yml#/components/securitySchemes"

tags:
  - name: Adapter Management
    description: Operations related to Adapter Management

paths:
  /adapter/claim:
    post:
      operationId: adapterClaim
      tags:
        - Adapter Management
      summary: Claim the specified adapter for the clients account.
      description: |-
        # Usage

        Claims the specified adapter and associates it with the clients account.
        The Claim can only succeed if the Adapter is not associated with an
        account.

        This API Call may also be used to replace an existing adapter, by
        specifying the existing adapters AdapterID.  In which case, the existing
        adapter will be unassociated from the clients account and the newly
        claimed adapter will replace it in its entirety.

        ## Parameters
          - **id**: The id of the adapter the client wants to claim.
          - **oldid**: Optional. Allows the claimed adapter t replace an
          existing adapter on the clients account.  In this instance, the old
          adapter becomes unassociated with any account, and the new adapter
          takes over the configuration, discovered devices and profiles of the
          old adapter.

      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - id
              additionalProperties: false
              properties:
                id:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
                oldid:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
            examples:
              new:
                value:
                  id: "d6faadd3-d339-4910-89b4-570ec9f72cb7"
                description: Claiming a new adapter.
              replacement:
                value:
                  id: "d6faadd3-d339-4910-89b4-570ec9f72cb7"
                  oldid: "cd73b915-89a4-4971-9d86-bce91786b12a"
                description: Replacing an existing adapter.

      responses:
        "200":
          description: |-
            Success, The claimed adapters details.

            - **AdapterID** - is the Unique ID of this Adapter.
            - **mac** - The Adapters mac address.
            - **ip** - list of ip addresses, either current, or last known.
            - **registered** - the time the adapter was first claimed by the
            customer.
            - **state** - the current state of the listed services.
            - **settings** - the current adapter level settings.
            - **health** - the last and best result from diagnostic tests.

          content:
            application/json:
              schema:
                $ref: "../../inc/adapter.oas3.yml#/components/schemas/Adapter"
        "400":
          description: |-
            General Request processing error.  Possible errors are:
            * `"Internal Server Error."` - Fatal uncategorized error in server.
            * `"Required Parameters missing or malformed."` - JSON Message Body
            Error.
            * `"Insecure Password"` - Password failed security strength check.
            * `"Old Password doesn't match"` - Old Password failed security check.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Internal Server Error."

        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "404":
          $ref: "../../inc/response.oas3.yml#/components/responses/404"
        "415":
          $ref: "../../inc/response.oas3.yml#/components/responses/415"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        default:
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
