openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /adapter/claim"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    Claim an Adapter for a client account.

    `/adapter/claim`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PHMothership.openapi.yml#/components/securitySchemes"

tags:
  - name: Adapter Management
    description: Operations related to Adapter Management

paths:
  /adapter/claim:
    post:
      operationId: adapterClaim
      tags:
        - Adapter Management
      summary: Claim the specified adapter for the clients account.
      description: |-
        Claims the specified adapter and associates it with the clients account.
        The Claim can only succeed if the Adapter is not associated with an
        account.

        This API Call may also be used to replace an existing adapter, by
        specifying the existing adapters AdapterID.  In which case, the existing
        adapter will be unassociated from the clients account and the newly
        claimed adapter will replace it in its entirety.

      externalDocs:
        url: "./API/flows/AdapterAccountAssociation-Flow.html"
        description: Adapter/Account Association message flow diagram.
      security:
        - clientToken: []

      parameters:
        - in: query
          name: mac
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/mac"
          example: "00-00-5E-DF-98-EB"
          description: |-
            The mac address of the adapter to associate with the account.
            Must not already be associated with another account.
        - in: query
          name: AdapterID
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
          example: "cd73b915-89a4-4971-9d86-bce91786b12a"
          description: |-
            IF the adapter is replacing an existing adapter, include the
            AdapterID of the Adapter to replace.  The AdapterID will not change
            but the Adapter will replace the existing adapter known by that ID.
            The old Adapter will then become unassociated from the client.

      responses:
        "200":
          description: |-
            Success, The claimed adapters details.

            - **AdapterID** - is the Unique ID of this Adapter.
            - **mac** - The Adapters mac address.
            - **ip** - list of ip addresses, either current, or last known.
            - **registered** - the time the adapter was first claimed by the
            customer.
            - **state** - the current state of the listed services.
            - **settings** - the current adapter level settings.
            - **diags** - the last and best result from diagnostic tests.


          content:
            application/json:
              schema:
                $ref: "../../inc/adapter.oas3.yml#/components/schemas/Adapter"

        "400":
          description: |-
            General Request processing error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Could not claim the adapter!"

        "403":
          description: |-
            Invalid Client Token, could not authorize api access.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/GW_NegAuth"

        "500":
          description: |-
            An Internal server error occurred.  Operation failed.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/GW_InternalError"
