openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /adapter/diag"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    Start an adapter diagnostic and Query diagnostic results.

    `/adapter/diag`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PH2-API.oas3.yml#/components/securitySchemes"

tags:
  - name: Adapter Management
    description: Operations related to Adapter Management

paths:
  /adapter/diag:
    get:
      operationId: adapterDiagQuery
      tags:
        - Adapter Management
      summary: Query the result of adapter diagnostics.
      description: |-
        # Usage

        When an adapter health diagnostic is running (or at any time) this api
        call may be made to get the current status of any running tests. AND to
        get the historical diagnostic/health results.

        ## Parameters
          - **id**: The id of the adapter to retrieve diagnostic health status
          from.
          - **days**: The maximum number of previous days to report. 1 = today.
          0 = The most recent "WAN" result only. (Note, if this parameter is not
          present, it defaults to 0.)

      parameters:
        - in: query
          name: id
          required: true
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
          example: "cd73b915-89a4-4971-9d86-bce91786b12a"
          description: |-
            The Adapter ID to Query.
        - in: query
          name: days
          required: false
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/health-days"
          example: 1
          description: |-
            The number of days of health history to provide. 1 is the most
            recent day.  0 = the most recent WAN Record. (Default)

      responses:
        "200":
          description: |-
            Success, Diagnostic Health Result returned.
          content:
            application/json:
              schema:
                $ref: "../../inc/adapter.oas3.yml#/components/schemas/Adapter-Diags"
              example:
                [
                  {
                    "timestamp": 1591886048,
                    "location-server": "Phuket, Thailand",
                    "provider": "3BB",
                    "distance": -50,
                    "latency": 5,
                    "latency-completion": 100,
                    "speed-rx": 185608437,
                    "speed-tx": 282140344,
                    "connection": "WAN",
                    "quality": "HIGH",
                  },
                  {
                    "timestamp": 1591884008,
                    "location-server": "Singapore",
                    "provider": "Singtel",
                    "distance": 600,
                    "latency": 36,
                    "latency-completion": 90,
                    "speed-rx": 185608437,
                    "speed-tx": 282140344,
                    "connection": "VPN",
                    "quality": "HIGH",
                  },
                  {
                    "timestamp": 1591799408,
                    "location-server": "Phuket, Thailand",
                    "provider": "3BB",
                    "distance": -50,
                    "latency": 5,
                    "latency-completion": 100,
                    "speed-rx": 185608437,
                    "speed-tx": 282140344,
                    "connection": "WAN",
                    "quality": "POOR",
                  },
                  {
                    "timestamp": 1591797608,
                    "location-server": "Singapore",
                    "provider": "Singtel",
                    "distance": 600,
                    "latency": 36,
                    "latency-completion": 90,
                    "speed-rx": 185608437,
                    "speed-tx": 282140344,
                    "connection": "VPN",
                    "quality": "LOW",
                  },
                ]
        "400":
          description: |-
            General Request processing error.  Possible errors are:
            * `"Internal Server Error."` - Fatal uncategorized error in server.
            * `"Required Parameters missing or malformed."` - JSON Message Body
            Error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Internal Server Error."
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "404":
          $ref: "../../inc/response.oas3.yml#/components/responses/404"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        "default":
          $ref: "../../inc/response.oas3.yml#/components/responses/default"

    post:
      operationId: adapterDiagStart
      tags:
        - Adapter Management
      summary: Start a diagnostic health check now.
      description: |-
        # Usage

        The system and adapters automatically run diagnostic health checks on a
        daily basis, however, if the client wishes to force an adapter to run a
        diagnostic health check now, this call can be made.

        ## Parameters
          - **id**: The id of the adapter to run the test on.  The Adapter must
          be registered to the current client.
          - **test**: The test to perform.
            - "**SpeedTest**" will automatically pick the most appropriate speedtest.com
            server and perform WAN and (if active) VPN speed tests, and update
            the health records.

      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - id
                - test
              additionalProperties: false
              properties:
                id:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
                test:
                  type: string
                  enum:
                    - "SpeedTest"

      responses:
        "200":
          description: |-
            Success, Current Diagnostic Health Result returned.
          content:
            application/json:
              schema:
                $ref: "../../inc/adapter.oas3.yml#/components/schemas/Adapter-Diag_Requested-Reply"

        "400":
          description: |-
            General Request processing error.  Possible errors are:
            * `"Internal Server Error."` - Fatal uncategorized error in server.
            * `"Required Parameters missing or malformed."` - JSON Message Body
            Error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Internal Server Error."
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "415":
          $ref: "../../inc/response.oas3.yml#/components/responses/415"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        "default":
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
