openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /adapter/diag"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    Start an adapter diagnostic and Query diagnostic results.

    `/adapter/diag`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PH2-API.oas3.yml#/components/securitySchemes"

tags:
  - name: Adapter Management
    description: Operations related to Adapter Management

paths:
  /adapter/diag:
    get:
      operationId: adapterDiagQuery
      tags:
        - Adapter Management
      summary: Query the result of adapter diagnostics.
      description: |-
        # Usage

        When an adapter health diagnostic is running (or at any time) this api
        call may be made to get the current status of any running tests. AND to
        get the historical diagnostic/health results.

        ## Parameters
          - **id**: The id of the adapter to retrieve diagnostic health status from.

      parameters:
        - in: query
          name: id
          required: true
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
          example: "cd73b915-89a4-4971-9d86-bce91786b12a"
          description: |-
            The Adapter ID to Query.
      responses:
        "200":
          description: |-
            Success, Diagnostic Health Result returned.
          content:
            application/json:
              schema:
                $ref: "../../inc/adapter.oas3.yml#/components/schemas/Adapter-Diags"
        "400":
          description: |-
            General Request processing error.  Possible errors are:
            * `"Internal Server Error."` - Fatal uncategorized error in server.
            * `"Required Parameters missing or malformed."` - JSON Message Body
            Error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Internal Server Error."
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "404":
          $ref: "../../inc/response.oas3.yml#/components/responses/404"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        "default":
          $ref: "../../inc/response.oas3.yml#/components/responses/default"

    post:
      operationId: adapterDiagStart
      tags:
        - Adapter Management
      summary: Start a diagnostic health check now.
      description: |-
        # Usage

        The system and adapters automatically run diagnostic health checks on a
        daily basis, however, if the client wishes to force an adapter to run a
        diagnostic health check now, this call can be made.

        ## Parameters
          - **id**: The id of the adapter to run the test on.  The Adapter must
          be registered to the current client.
          - **test**: The test to perform.
            - "**SpeedTest**" will automatically pick the closest speedtest.com
            server to the adapter and complete the speed test check.
            - "**BasicConnectivity**" will cause a series of pings to be sent to
                 a wel known and reliable server.  The time taken to reply and
                 the number of replies which fail to be received will be recorded.

      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - id
                - test
              additionalProperties: false
              properties:
                id:
                  $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
                test:
                  type: string
                  enum:
                    - "SpeedTest"
                    - "BasicConnectivity"


      responses:
        "200":
          description: |-
            Success, Current Diagnostic Health Result returned.
          content:
            application/json:
              schema:
                $ref: "../../inc/adapter.oas3.yml#/components/schemas/Adapter-Diags"

        "400":
          description: |-
            General Request processing error.  Possible errors are:
            * `"Internal Server Error."` - Fatal uncategorized error in server.
            * `"Required Parameters missing or malformed."` - JSON Message Body
            Error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Internal Server Error."
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "415":
          $ref: "../../inc/response.oas3.yml#/components/responses/415"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        "default":
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
