openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /adapter/find"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    Find an unassociated adapter.

    `/adapter/find`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PH2-API.oas3.yml#/components/securitySchemes"

tags:
  - name: Adapter Management
    description: Operations related to Adapter Management

paths:
  /adapter/find:
    get:
      operationId: adapterFind
      tags:
        - Adapter Management
      summary: Find Unassociated adapters we can bind the client account to.
      description: |-
        # Usage
        When an adapter is first installed, it is not linked to an account.
        The client must add the adapter to their account, this function will
        return a list of adapters which are available to be associated.

        It will either find all adapters on the same local network as the client
        connection.  Or if that does not work, an adapter with a specific
        activation code.

        ## Security Requirements
          - **appKey** **MUST NOT** be present in the call.
          - **clientToken** **MUST** be present, not in need of renewal and valid.

        ## Parameters
          - **code**: This is the optional activation code.  If not set, the
            function will look for all unassociated adapters that share the
            internet connection of the client making the call.

            However, IF that fails, this can be set to a known activation code
            which will cause any adapter with the matching activation code which
            is not currently associated with an account to be returned.
            Typically this would be a single Adapter.  If no adapters are found,
            a "404" response will be generated.

      parameters:
        - in: query
          required: false
          name: code
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/activation-code"
          description: |-
            The optional adapters activation code.

      responses:
        "200":
          description: |-
            The list of all unclaimed adapters.
              - **id**: Unique ID for the adapter (used in other API calls to
              reference this adapter.)
              - **adapter**: Identifying information for the adapter.
                - **mac**: Adapters hardware mac address
                - **type**: The type of adapter hardware.
                - **desc**: Long form description of the adapter hardware.
              - **since**: This is the epoch time when the unassociated adapter
              last connected with the backend.
          content:
            application/json:
              schema:
                $ref: "../../inc/adapter.oas3.yml#/components/schemas/Adapter-Unassociated-Array"

        "400":
          description: |-
            General Request processing error.  Possible errors are:
            * `"Internal Server Error."` - Fatal uncategorized error in server.
            * `"Required Parameters missing or malformed."` - JSON Message Body
            Error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Internal Server Error."
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "404":
          $ref: "../../inc/response.oas3.yml#/components/responses/404"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        default:
          $ref: "../../inc/response.oas3.yml#/components/responses/default"

