openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /adapter/list"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    List one or all adapters on an account.

    `/adapter/list`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PH2-API.oas3.yml#/components/securitySchemes"

tags:
  - name: Adapter Management
    description: Operations related to Adapter Management

paths:
  /adapter/list:
    get:
      operationId: adapterList
      tags:
        - Adapter Management
      summary: Lists one or all adapters associated with the clients account.
      description: |-
        # Usage
        Generates a list of adapters associated with the clients account.
        Can list a single adapter, or all adapters associated with the account.
        In the case that a client has no adapters associated, this will be an
        empty list.

        ## Security Requirements
          - **appKey** **MUST NOT** be present in the call.
          - **clientToken** **MUST** be present, not in need of renewal and valid.

        ## Parameters
          - **id**: Optional, the ID of the adapter, if only one adapters
          information is being requested.  Only adapters associated with a
          clients account can be returned with this call.  IF the id is valid,
          but the adapter is not associated with this clients account, then that
          is treated the same as the adapter ID being invalid.

      parameters:
        - in: query
          name: id
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
          example: "cd73b915-89a4-4971-9d86-bce91786b12a"
          description: |-
            The Adapter ID to list.  IF not present, will return ALL Adapters
            associated with the Clients account.

      responses:
        "200":
          description: |-
            Success, The adapters details.

            - **AdapterID** - is the Unique ID of this Adapter.
            - **mac** - The Adapters mac address.
            - **ip** - list of ip addresses, either current, or last known.
            - **registered** - the time the adapter was first claimed by the
            customer.
            - **state** - the current state of the listed services.
            - **settings** - the current adapter level settings.
            - **health** - the last and best result from diagnostic tests.

          content:
            application/json:
              schema:
                $ref: "../../inc/adapter.oas3.yml#/components/schemas/Adapters"

        "400":
          description: |-
            General Request processing error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Could not find the adapter!"
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "404":
          $ref: "../../inc/response.oas3.yml#/components/responses/404"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        default:
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
