openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /adapter/list"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    List all adapters on an account.

    **_EARLY DRAFT_**

    `/adapter/list`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PHMothership.openapi.yml#/components/securitySchemes"

tags:
  - name: Adapter Management
    description: Operations related to Adapter Management

paths:
  /adapter/list:
    get:
      operationId: adapterList
      tags:
        - Adapter Management
      summary: Lists all adapters associated with the clients account.
      description: |-
        Generates a list of all adapters associated with the clients account.

        **_EARLY DRAFT_**
      externalDocs:
        url: "./API/flows/AdapterAccountAssociation-Flow.html"
        description: Adapter/Account Association message flow diagram.
      security:
        - clientToken: []

      parameters:
        - in: query
          name: devices
          schema:
            type: boolean
            default: false
          example: true
          description: |-
            If devices is not present, or false, then the response will just
            list the known adapters.  If it is true, the list will include every
            device known to those adapters.

      responses:
        "200":
          description: |-
            Success, The claimed adapters details.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "../../inc/components.oas3.yml#/components/schemas/Adapters"
                  - $ref: "../../inc/components.oas3.yml#/components/schemas/AdaptersDevices"

        "400":
          description: |-
            General Request processing error.
          content:
            application/json:
              schema:
                $ref: "../../inc/components.oas3.yml#/components/schemas/Nack"
              example:
                error: "Could not claim the adapter!"

        "403":
          description: |-
            Invalid Client Token, could not authorize api access.
          content:
            application/json:
              schema:
                $ref: "../../inc/components.oas3.yml#/components/schemas/GW_NegAuth"

        "500":
          description: |-
            An Internal server error occurred.  Operation failed.
          content:
            application/json:
              schema:
                $ref: "../../inc/components.oas3.yml#/components/schemas/GW_InternalError"
