openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /adapter/name"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    Give the adapter a name.

    `/adapter/name`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PHMothership.openapi.yml#/components/securitySchemes"

tags:
  - name: Adapter Management
    description: Operations related to Adapter Management

paths:
  /adapter/name:
    post:
      operationId: adapterName
      tags:
        - Adapter Management
      summary: Give an adapter a descriptive name.
      description: |-
        Provides a descriptive name to an adapter that helps identify it.
      security:
        - clientToken: []

      parameters:
        - in: query
          name: id
          required: true
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
          example: "cd73b915-89a4-4971-9d86-bce91786b12a"
          description: |-
            The Adapter ID to Name.

        - in: query
          name: name
          required: true
          schema:
            type: string
            nullable: true
          example: "Home Office Adapter"
          description: |-
            The name to apply to the adapter.

      responses:
        "200":
          description: |-
            Success, Adapter named.

        "400":
          description: |-
            General Request processing error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Could not name the adapter!"

        "401":
          description: |-
            The Clients Bearer Token is invalid or not recognized.
          headers:
            WWW-Authenticate:
              schema:
                type: string
                example: Bearer realm=privacyhero2.api.com
                description: |-
                  indicates the authentication scheme(s) and parameters
                  applicable to the target resource.

        "403":
          description: |-
            Invalid Client Token, could not authorize api access.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/GW_NegAuth"
        "415":
          description: |-
            Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"

        "429":
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"

        "500":
          description: |-
            An Internal server error occurred.  Operation failed.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/GW_InternalError"
