openapi: 3.0.1
info:
  title: "Privacy Hero 2 - Mothership API - /adapter/usage"
  version: "1.0"
  description: |-
    Privacy Hero 2 API.

    Generate a data usage report for an adapter.

    `/adapter/usage`
  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: ./LICENSE.md
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

components:
  securitySchemes:
    $ref: "../../PH2-API.oas3.yml#/components/securitySchemes"

tags:
  - name: Adapter Management
    description: Operations related to Adapter Management

paths:
  /adapter/usage:
    get:
      operationId: adapterUsage
      tags:
        - Adapter Management
      summary: Get device data usage.
      description: |-
        # Usage

        Generates a list of data usage values for an adapter, at a specified
        resolution.  Adapter usage is a measurer of actual traffic through an
        adapter and may not be the same value as the aggregated device usage on
        an adapter (It should not be less).  Deletion of devices, or their
        movement between profiles does not have an impact on the device usage
        figures.

        ## Parameters
          - **id**: The Unique adapter ID.
          - **resolution**: The resolution of the report.
          - **start**: The earliest time to report (is rounded down to the
          beginning of the resolution period the time appears within)
          - **end**: The latest time to report (is rounded up to the end of the
          resolution period the time appears within)

          Note, Resolution will always return a full period, so a monthly report
          will always return full months, and the data will be aligned with the
          billing period set in the adapter datacap configuration.

        ## Predicted values
          If a period or range extends into the future, the API will attempt to
          predict usage, based on previous usage history.  That usage will be
          reported as a negative value (to distinguish it from a known usage
          value)  Because a period may include both a known and a predicted
          component, in those cases, the period will be reported twice.  Firstly
          with the known usage in the period, and secondly with the predicted
          usage for that period.  The sum of the two values is the total usage
          the API guesses will be used in the period. (ie, prediction does not
          include the known data usage, only the extra predicted usage).

          Prediction will only extend up until the end of the current billing
          period, after the current billing periods future expiry date, no
          future predicted usage values will be returned.

      parameters:
        - in: query
          name: id
          required: true
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/uuid"
          description: |-
            The unique adapter id.
        - in: query
          name: resolution
          schema:
            type: string
            enum:
              - "Hourly"
              - "Daily"
              - "Weekly"
              - "Monthly"
            default: "Hourly"
          description: |-
            The time resolution to report. Hourly is hourly, Daily is 24 hours.
            Weekly is 7 days and Monthly is the full month aligned to the
            billing period.  If not specified the resolution is "Hourly"

        - in: query
          name: start
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/epoch-timestamp"
          description: |-
            The start of the reporting window.  If not specified, defaults to
            the oldest data on record for the device.

        - in: query
          name: end
          schema:
            $ref: "../../inc/simpletypes.oas3.yml#/components/schemas/epoch-timestamp"
          description: |-
            The end of the reporting window.  If not specified, defaults to
            now.


      responses:
        "200":
          description: |-
            Success, The adapters data usage is returned.
          content:
            application/json:
              schema:
                $ref: "../../inc/adapter.oas3.yml#/components/schemas/Adapter-Usage-History"
              example: [
                {
                  "timestamp": 1591918680,
                  "tx": 128974848,
                  "rx": 268435456
                },
                {
                  "timestamp": 1591918680,
                  "tx": -64487424,
                  "rx": -134217728
                },
                {
                  "timestamp": 1589119208,
                  "tx": 212808499,
                  "rx": 442918502
                },
              ]


        "400":
          description: |-
            General Request processing error.  Possible errors are:
            * `"Internal Server Error."` - Fatal uncategorized error in server.
            * `"Required Parameters missing or malformed."` - JSON Message Body
            Error.
          content:
            application/json:
              schema:
                $ref: "../../inc/response.oas3.yml#/components/schemas/Nack"
              example:
                error: "Internal Server Error."
        "401":
          $ref: "../../inc/response.oas3.yml#/components/responses/401"
        "403":
          $ref: "../../inc/response.oas3.yml#/components/responses/403"
        "404":
          $ref: "../../inc/response.oas3.yml#/components/responses/404"
        "429":
          $ref: "../../inc/response.oas3.yml#/components/responses/429"
        "500":
          $ref: "../../inc/response.oas3.yml#/components/responses/500"
        "default":
          $ref: "../../inc/response.oas3.yml#/components/responses/default"
