###### HEADER INFO ##################
openapi: "3.0.2"
info:
  title: "Privacy Hero 2 - Mothership API"
  version: "0.0.7"
  description: |-
    The complete backend API for the Privacy Hero 2.

    The backend server infrastructure is known as the *"Mothership"*

    This API Documentation may be viewed at:
      - **[PrivacyHero2 API - RapiDoc/PDF](.)**
      - [PrivacyHero2 API - Swagger UI](./index-swui.html)
      - [PrivacyHero2 API - Redocly](./index-redocly.html)
      - [Download API JSON](./API/PH2-API.oas3.json)

  license:
    name: Copyright © 2020 HelpOn Inc. All Rights Reserved
    url: "http://privacy-hero.github.io/ph2-apidocs/LICENSE.html"
  contact:
    name: API Support (Steven Johnson)
    url: http://www.example.com/support
    email: sakurainds@gmail.com

###### THE SERVERS WHERE THIS API CAN BE USED ############
servers:
  - url: https://api2.privacyhero.com/{stage} # what is our URL???
    description: The API deployment URL.
    variables:
      stage:
        enum:
          - dev
          - qa
          - prod
        default: prod
        description: Deployment Stages
  - url: https://{awsid}.execute-api.us-east-1.amazonaws.com/dev
    description: Development URL
    variables:
      awsid:
        default: "999999"
        description: The ID for your dev AWS deployment

#########################################################
# Components are preformatted data that can be reused in definitions.
components:
  # All Schemas are defined in ./inc/components.yml
  schemas: {}

  securitySchemes:
    clientToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |-
        Client Authorization Token, as generated by this API.
        - See the **Account Management** section for details.

    appKey:
      type: apiKey
      in: header
      name: X-API-KEY
      description: |-
        Application Unique API Key.

        - This key is distributed to authorized app developers and uniquely
        identifies the application.
        - API Keys **MUST NOT** be shared between end user applications.
        - Each end user application **MUST** use a unique key.
        - The **X-API-KEY** token **MUST** only be included in messages which
        require it.
        - If it is included in any other message, that message **WILL** fail to authenticate.

security:
  - clientToken: []

tags:
  - name: Account Management
    description: Operations related to Account Creation and Management
  - name: Client Management
    description: Operations related to the Client
  - name: Adapter Management
    description: Operations related to Adapter Management
  - name: Profile Management
    description: Operations related to Profile Management
  - name: Device Management
    description: Operations related to Device Management
  - name: Streaming Relocation Management
    description: Operations related to Streaming Services and Relocation

paths:

  ######### AUTHORIZATION API CALLS #########################

  /v1/auth/newcustomer: # Causes a new customer email to be sent
    $ref: "v1/auth/newcustomer.oas3.yml#/paths/~1auth~1newcustomer"

  /callback/path: # Called when the customer clicks the link in the new customer email.
    $ref: "v1/auth/emailcallback.oas3.yml#/paths/~1callback"

  /v1/auth/confirmcustomer:
    $ref: "v1/auth/confirmcustomer.oas3.yml#/paths/~1auth~1confirmcustomer"

  /v1/auth/login: # Logs in with a password
    $ref: "v1/auth/login.oas3.yml#/paths/~1auth~1login"

  /v1/auth/renew: # Renews an expired token, which is still in time for renewal
    $ref: "v1/auth/renew.oas3.yml#/paths/~1auth~1renew"

  /v1/auth/chgpwd: # Change the users password
    $ref: "v1/auth/chgpwd.oas3.yml#/paths/~1auth~1chgpwd"

  /v1/auth/chgemail: # change the users email address
    $ref: "v1/auth/chgemail.oas3.yml#/paths/~1auth~1chgemail"

  /v1/auth/delcustomer: # delete the customer
    $ref: "v1/auth/delcustomer.oas3.yml#/paths/~1auth~1delcustomer"

  ######### CLIENT MANAGEMENT API CALLS ######################

  /v1/client/notify:
    $ref: "v1/client/notify.oas3.yml#/paths/~1client~1notify"

  ######### ADAPTER  MANAGEMENT API CALLS ######################

  /v1/adapter/find:
    $ref: "v1/adapter/find.oas3.yml#/paths/~1adapter~1find"

  /v1/adapter/claim:
    $ref: "v1/adapter/claim.oas3.yml#/paths/~1adapter~1claim"

  /v1/adapter/list:
    $ref: "v1/adapter/list.oas3.yml#/paths/~1adapter~1list"

  /v1/adapter/cfg:
    $ref: "v1/adapter/cfg.oas3.yml#/paths/~1adapter~1cfg"

  /v1/adapter/cfg/service:
    $ref: "v1/adapter/cfg-service.oas3.yml#/paths/~1adapter~1cfg~1service"

  /v1/adapter/cfg/name:
    $ref: "v1/adapter/cfg-name.oas3.yml#/paths/~1adapter~1cfg~1name"

  /v1/adapter/cfg/locale:
    $ref: "v1/adapter/cfg-locale.oas3.yml#/paths/~1adapter~1cfg~1locale"

  /v1/adapter/cfg/datacap:
    $ref: "v1/adapter/cfg-datacap.oas3.yml#/paths/~1adapter~1cfg~1datacap"

  /v1/adapter/cfg/wifi:
    $ref: "v1/adapter/cfg-wifi.oas3.yml#/paths/~1adapter~1cfg~1wifi"

  /v1/adapter/health:
    $ref: "v1/adapter/diag.oas3.yml#/paths/~1adapter~1diag"

  /v1/adapter/datausage:
    $ref: "v1/adapter/datausage.oas3.yml#/paths/~1adapter~1datausage"

  ######### STREAMING MANAGEMENT API CALLS ######################

  /v1/streaming/services:
    $ref: "v1/streaming/services.oas3.yml#/paths/~1streaming~1services"

  /v1/streaming/cfg:
    $ref: "v1/streaming/cfg.oas3.yml#/paths/~1streaming~1cfg"


  ######### PROFILE  MANAGEMENT API CALLS ######################

  /v1/profile/list:
    $ref: "v1/profile/list.oas3.yml#/paths/~1profile~1list"

  /v1/profile/create:
    $ref: "v1/profile/create.oas3.yml#/paths/~1profile~1create"

  /v1/profile/delete:
    $ref: "v1/profile/delete.oas3.yml#/paths/~1profile~1delete"

  /v1/profile/cfg/name:
    $ref: "v1/profile/cfg-name.oas3.yml#/paths/~1profile~1cfg~1name"

  /v1/profile/cfg/bedtimes:
    $ref: "v1/profile/cfg-bedtimes.oas3.yml#/paths/~1profile~1cfg~1bedtimes"

  /v1/profile/cfg/bedtime-delay:
    $ref: "v1/profile/cfg-bedtime-delay.oas3.yml#/paths/~1profile~1cfg~1bedtime-delay"

  /v1/profile/cfg/setting:
    $ref: "v1/profile/cfg-setting.oas3.yml#/paths/~1profile~1cfg~1setting"

  /v1/profile/device:
    $ref: "v1/profile/device.oas3.yml#/paths/~1profile~1device"

  ######### DEVICE  MANAGEMENT API CALLS ######################

  /v1/device/list:
    $ref: "v1/device/list.oas3.yml#/paths/~1device~1list"

  /v1/device/assign:
    $ref: "v1/device/assign.oas3.yml#/paths/~1device~1assign"

  /v1/device/usage:
    $ref: "v1/device/usage.oas3.yml#/paths/~1device~1usage"

  #/v1/device/name
  # Change name, type and manufacturer

  # vpn on/off (pause timed/unpause)
  # adblocking on/off (pause timed/unpause)
  # device protection on/off (pause/unpause internet)

